In [124]:
!git clone https://github.com/cuhksz-nlp/R2Gen.git
%cd R2Gen

!pip install kagglehub
import kagglehub
path = kagglehub.dataset_download("raddar/chest-xrays-indiana-university")
print(path)

Cloning into 'R2Gen'...
remote: Enumerating objects: 89, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 89 (delta 14), reused 14 (delta 14), pack-reused 61 (from 1)
Receiving objects: 100% (89/89), 70.19 MiB | 10.69 MiB/s, done.
Resolving deltas: 100% (27/27), done.
/home/jupyter-st126671/R2Gen/R2Gen

/opt/tljh/user/lib/python3.12/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kagglehub in /home/jupyter-st126671/.local/lib/python3.12/site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in /home/jupyter-st126671/.local/lib/python3.12/site-packages (from kagglehub) (0.1.19)
Requirement already satisfied: packaging in /opt/tljh/user/lib/python3.12/site-packages (from kagglehub) (24.1)
Requirement already satisfied: pyyaml in /opt/tljh/user/lib/python3.12/site-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in /opt/tljh/user/lib/python3.12/site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in /opt/tljh/user/lib/python3.12/site-packages (from kagglehub) (4.66.5)
Requirement already satisfied: protobuf in /home/jupyter-st126671/.local/lib/python3.12/site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (7.34.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/tljh/user/lib/python3.12/site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/tljh/user/lib/python3.12/site-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/tljh/user/lib/python3.12/site-packages (from requests->kagglehub) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/tljh/user/lib/python3.12/site-packages (from requests->kagglehub) (2024.12.14)
/home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2

In [125]:
import os
from pathlib import Path

root = Path(path)   # 'path' is from kagglehub.dataset_download(...)

print("Dataset root:", root)
print("\nTop-level files/folders:")
for p in sorted(root.iterdir()):
    print("-", p.name)

print("\nSample tree (2 levels):")
for p in sorted(root.rglob("*")):
    rel = p.relative_to(root)
    if len(rel.parts) <= 2:
        print(rel)

Dataset root: /home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2

Top-level files/folders:
- images
- indiana_projections.csv
- indiana_reports.csv

Sample tree (2 levels):
images
images/images_normalized
indiana_projections.csv
indiana_reports.csv

In [126]:
import pandas as pd

png_files = list(root.rglob("*.png"))
print("PNG files:", len(png_files))

PNG files: 7470

In [127]:
from pathlib import Path
import shutil

# If your notebook is inside the R2Gen folder already
project_root = Path.cwd()

# If your notebook is outside and you want a subfolder named R2Gen instead, use:
# project_root = Path.cwd() / "R2Gen"

iu_root = project_root / "data" / "iu_xray"
images_dst = iu_root / "images"

iu_root.mkdir(parents=True, exist_ok=True)
images_dst.mkdir(parents=True, exist_ok=True)

print("project_root =", project_root.resolve())
print("Created:", iu_root.resolve())
print("Created:", images_dst.resolve())

project_root = /home/jupyter-st126671/R2Gen/R2Gen
Created: /home/jupyter-st126671/R2Gen/R2Gen/data/iu_xray
Created: /home/jupyter-st126671/R2Gen/R2Gen/data/iu_xray/images

In [128]:
from pathlib import Path
import shutil

# your project folder
project_root = Path.cwd()

# source folder where your original images are located
root = project_root / "your_source_images_folder"

# destination folder for R2Gen
iu_root = project_root / "data" / "iu_xray"
images_dst = iu_root / "images"

# create destination folders
images_dst.mkdir(parents=True, exist_ok=True)

src_exts = {".png", ".jpg", ".jpeg"}
image_files = [p for p in root.rglob("*") if p.suffix.lower() in src_exts]

print("Source folder:", root.resolve())
print("Found images:", len(image_files))

copied = 0
for img in image_files:
    dst = images_dst / img.name
    if not dst.exists():
        shutil.copy2(img, dst)
        copied += 1

print("Copied images:", copied)
print("Total now in destination:", len(list(images_dst.glob("*"))))

Source folder: /home/jupyter-st126671/R2Gen/R2Gen/your_source_images_folder
Found images: 0
Copied images: 0
Total now in destination: 0

In [129]:
from pathlib import Path
import shutil

project_root = Path.cwd()

root = Path("/home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/images/images_normalized")
images_dst = project_root / "data" / "iu_xray" / "images"

images_dst.mkdir(parents=True, exist_ok=True)

src_exts = {".png", ".jpg", ".jpeg"}
image_files = [p for p in root.rglob("*") if p.suffix.lower() in src_exts]

print("Source folder:", root)
print("Found images:", len(image_files))

copied = 0
for idx, img in enumerate(image_files, start=1):
    dst = images_dst / img.name
    if not dst.exists():
        shutil.copy2(img, dst)
        copied += 1

    if idx % 500 == 0:
        print(f"Processed {idx}/{len(image_files)} | Copied {copied}")

print("Done")
print("Copied images:", copied)
print("Total now in destination:", len(list(images_dst.iterdir())))

Source folder: /home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/images/images_normalized
Found images: 7470
Processed 500/7470 | Copied 500
Processed 1000/7470 | Copied 1000
Processed 1500/7470 | Copied 1500
Processed 2000/7470 | Copied 2000
Processed 2500/7470 | Copied 2500
Processed 3000/7470 | Copied 3000
Processed 3500/7470 | Copied 3500
Processed 4000/7470 | Copied 4000
Processed 4500/7470 | Copied 4500
Processed 5000/7470 | Copied 5000
Processed 5500/7470 | Copied 5500
Processed 6000/7470 | Copied 6000
Processed 6500/7470 | Copied 6500
Processed 7000/7470 | Copied 7000
Done
Copied images: 7470
Total now in destination: 7470

In [130]:
from pathlib import Path
import pandas as pd

dataset_root = Path("/home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2")

csv_files = list(dataset_root.rglob("*.csv"))

print("CSV files found:")
for i, f in enumerate(csv_files):
    print(i, f)

for f in csv_files:
    print("\n---", f.name, "---")
    try:
        df = pd.read_csv(f)
        print("shape:", df.shape)
        print("columns:", list(df.columns))
        print(df.head(2))
    except Exception as e:
        print("Could not read:", e)

CSV files found:
0 /home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_reports.csv
1 /home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_projections.csv

--- indiana_reports.csv ---
shape: (3851, 8)
columns: ['uid', 'MeSH', 'Problems', 'image', 'indication', 'comparison', 'findings', 'impression']
   uid                                               MeSH  \
0    1                                             normal
1    2  Cardiomegaly/borderline;Pulmonary Artery/enlarged

                        Problems                                image  \
0                         normal            Xray Chest PA and Lateral
1  Cardiomegaly;Pulmonary Artery  Chest, 2 views, frontal and lateral

                 indication comparison  \
0          Positive TB test      None.
1  Preop bariatric surgery.      None.

                                            findings  \
0  The cardiac silhouette and mediastinum size ar...
1  Borderline cardiomegaly. Midline sternotomy XX...

                     impression
0          Normal chest x-XXXX.
1  No acute pulmonary findings.

--- indiana_projections.csv ---
shape: (7466, 3)
columns: ['uid', 'filename', 'projection']
   uid                filename projection
0    1  1_IM-0001-4001.dcm.png    Frontal
1    1  1_IM-0001-3001.dcm.png    Lateral

In [131]:
report_csv = None

for f in csv_files:
    if "report" in f.name.lower() or "indiana" in f.name.lower():
        report_csv = f
        break

print("Selected CSV:", report_csv)

df = pd.read_csv(report_csv)
print(df.columns.tolist())
print(df.head())

Selected CSV: /home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_reports.csv
['uid', 'MeSH', 'Problems', 'image', 'indication', 'comparison', 'findings', 'impression']
   uid                                               MeSH  \
0    1                                             normal
1    2  Cardiomegaly/borderline;Pulmonary Artery/enlarged
2    3                                             normal
3    4  Pulmonary Disease, Chronic Obstructive;Bullous...
4    5  Osteophyte/thoracic vertebrae/multiple/small;T...

                                            Problems  \
0                                             normal
1                      Cardiomegaly;Pulmonary Artery
2                                             normal
3  Pulmonary Disease, Chronic Obstructive;Bullous...
4                         Osteophyte;Thickening;Lung

                                               image  \
0                          Xray Chest PA and Lateral
1                Chest, 2 views, frontal and lateral
2                          Xray Chest PA and Lateral
3  PA and lateral views of the chest XXXX, XXXX a...
4                          Xray Chest PA and Lateral

                                          indication      comparison  \
0                                   Positive TB test           None.
1                           Preop bariatric surgery.           None.
2  rib pain after a XXXX, XXXX XXXX steps this XX...             NaN
3                      XXXX-year-old XXXX with XXXX.  None available
4                        Chest and nasal congestion.             NaN

                                            findings  \
0  The cardiac silhouette and mediastinum size ar...
1  Borderline cardiomegaly. Midline sternotomy XX...
2                                                NaN
3  There are diffuse bilateral interstitial and a...
4  The cardiomediastinal silhouette and pulmonary...

                                          impression
0                               Normal chest x-XXXX.
1                       No acute pulmonary findings.
2  No displaced rib fractures, pneumothorax, or p...
3  1. Bullous emphysema and interstitial fibrosis...
4              No acute cardiopulmonary abnormality.

In [132]:
import pandas as pd
from pathlib import Path

dataset_root = Path("/home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2")

csv_files = list(dataset_root.rglob("*.csv"))

print("CSV files found:")
for i, f in enumerate(csv_files):
    print(i, f)

if len(csv_files) == 0:
    print("\nNo CSV files found.")
else:
    report_csv = csv_files[0]
    df = pd.read_csv(report_csv)

    print("\nSelected CSV:", report_csv)
    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())
    print("\nHead:")
    display(df.head())

CSV files found:
0 /home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_reports.csv
1 /home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_projections.csv

Selected CSV: /home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_reports.csv
Shape: (3851, 8)
Columns: ['uid', 'MeSH', 'Problems', 'image', 'indication', 'comparison', 'findings', 'impression']

Head:

,uid,MeSH,Problems,image,indication,comparison,findings,impression
0,1,normal,normal,Xray Chest PA and Lateral,Positive TB test,None.,The cardiac silhouette and mediastinum size ar...,Normal chest x-XXXX.
1,2,Cardiomegaly/borderline;Pulmonary Artery/enlarged,Cardiomegaly;Pulmonary Artery,"Chest, 2 views, frontal and lateral",Preop bariatric surgery.,None.,Borderline cardiomegaly. Midline sternotomy XX...,No acute pulmonary findings.
2,3,normal,normal,Xray Chest PA and Lateral,"rib pain after a XXXX, XXXX XXXX steps this XX...",NaN,NaN,"No displaced rib fractures, pneumothorax, or p..."
3,4,"Pulmonary Disease, Chronic Obstructive;Bullous...","Pulmonary Disease, Chronic Obstructive;Bullous...","PA and lateral views of the chest XXXX, XXXX a...",XXXX-year-old XXXX with XXXX.,None available,There are diffuse bilateral interstitial and a...,1. Bullous emphysema and interstitial fibrosis...
4,5,Osteophyte/thoracic vertebrae/multiple/small;T...,Osteophyte;Thickening;Lung,Xray Chest PA and Lateral,Chest and nasal congestion.,NaN,The cardiomediastinal silhouette and pulmonary...,No acute cardiopulmonary abnormality.

In [133]:
# Check missing values in likely important columns
candidate_cols = [c for c in df.columns if c.lower() in ["uid", "id", "findings", "impression", "image", "filename", "problems"]]
print("Candidate columns:", candidate_cols)

for c in candidate_cols:
    print(f"{c}: missing =", df[c].isna().sum())

Candidate columns: ['uid', 'Problems', 'image', 'findings', 'impression']
uid: missing = 0
Problems: missing = 0
image: missing = 0
findings: missing = 514
impression: missing = 31

In [134]:
import pandas as pd
from pathlib import Path

dataset_root = Path("/home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2")

csv_files = list(dataset_root.rglob("*.csv"))

print("CSV files found:")
for i, f in enumerate(csv_files):
    print(i, f)

if len(csv_files) == 0:
    print("\nNo CSV files found.")
else:
    report_csv = csv_files[0]
    df = pd.read_csv(report_csv)

    print("\nSelected CSV:", report_csv)
    print("\nExact columns:")
    for i, c in enumerate(df.columns):
        print(i, repr(c))

CSV files found:
0 /home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_reports.csv
1 /home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_projections.csv

Selected CSV: /home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_reports.csv

Exact columns:
0 'uid'
1 'MeSH'
2 'Problems'
3 'image'
4 'indication'
5 'comparison'
6 'findings'
7 'impression'

In [135]:
import pandas as pd
from pathlib import Path

dataset_root = Path("/home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2")

reports_csv = dataset_root / "indiana_reports.csv"
projections_csv = dataset_root / "indiana_projections.csv"

print("Reports exists:", reports_csv.exists(), reports_csv)
print("Projections exists:", projections_csv.exists(), projections_csv)

reports_df = pd.read_csv(reports_csv)
proj_df = pd.read_csv(projections_csv)

reports_df.columns = [c.strip() for c in reports_df.columns]
proj_df.columns = [c.strip() for c in proj_df.columns]

print("Reports columns:")
for i, c in enumerate(reports_df.columns):
    print(i, repr(c))

print("\nProjections columns:")
for i, c in enumerate(proj_df.columns):
    print(i, repr(c))

print("\nReports head:")
display(reports_df.head())

print("\nProjections head:")
display(proj_df.head())

Reports exists: True /home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_reports.csv
Projections exists: True /home/jupyter-st126671/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_projections.csv
Reports columns:
0 'uid'
1 'MeSH'
2 'Problems'
3 'image'
4 'indication'
5 'comparison'
6 'findings'
7 'impression'

Projections columns:
0 'uid'
1 'filename'
2 'projection'

Reports head:

,uid,MeSH,Problems,image,indication,comparison,findings,impression
0,1,normal,normal,Xray Chest PA and Lateral,Positive TB test,None.,The cardiac silhouette and mediastinum size ar...,Normal chest x-XXXX.
1,2,Cardiomegaly/borderline;Pulmonary Artery/enlarged,Cardiomegaly;Pulmonary Artery,"Chest, 2 views, frontal and lateral",Preop bariatric surgery.,None.,Borderline cardiomegaly. Midline sternotomy XX...,No acute pulmonary findings.
2,3,normal,normal,Xray Chest PA and Lateral,"rib pain after a XXXX, XXXX XXXX steps this XX...",NaN,NaN,"No displaced rib fractures, pneumothorax, or p..."
3,4,"Pulmonary Disease, Chronic Obstructive;Bullous...","Pulmonary Disease, Chronic Obstructive;Bullous...","PA and lateral views of the chest XXXX, XXXX a...",XXXX-year-old XXXX with XXXX.,None available,There are diffuse bilateral interstitial and a...,1. Bullous emphysema and interstitial fibrosis...
4,5,Osteophyte/thoracic vertebrae/multiple/small;T...,Osteophyte;Thickening;Lung,Xray Chest PA and Lateral,Chest and nasal congestion.,NaN,The cardiomediastinal silhouette and pulmonary...,No acute cardiopulmonary abnormality.

Projections head:

   uid                filename projection
0    1  1_IM-0001-4001.dcm.png    Frontal
1    1  1_IM-0001-3001.dcm.png    Lateral
2    2  2_IM-0652-1001.dcm.png    Frontal
3    2  2_IM-0652-2001.dcm.png    Lateral
4    3  3_IM-1384-1001.dcm.png    Frontal

In [136]:
lower_map_reports = {c.lower(): c for c in reports_df.columns}

print(lower_map_reports)

ID_COL = lower_map_reports.get("uid")
TARGET_COL = lower_map_reports.get("impression")

print("ID_COL =", ID_COL)
print("TARGET_COL =", TARGET_COL)

{'uid': 'uid', 'mesh': 'MeSH', 'problems': 'Problems', 'image': 'image', 'indication': 'indication', 'comparison': 'comparison', 'findings': 'findings', 'impression': 'impression'}
ID_COL = uid
TARGET_COL = impression

In [137]:
print("Columns in reports_df:")
for i, c in enumerate(reports_df.columns):
    print(i, repr(c))

Columns in reports_df:
0 'uid'
1 'MeSH'
2 'Problems'
3 'image'
4 'indication'
5 'comparison'
6 'findings'
7 'impression'

In [138]:
ID_COL = "uid"          # change if needed
TARGET_COL = "findings" # or "impression", depending on your task

In [139]:
reports_clean = reports_df.copy()

reports_clean = reports_clean[reports_clean[TARGET_COL].notna()]
reports_clean[TARGET_COL] = reports_clean[TARGET_COL].astype(str).str.strip()
reports_clean = reports_clean[reports_clean[TARGET_COL] != ""]

print("Rows with valid impression:", len(reports_clean))
display(reports_clean[[ID_COL, TARGET_COL]].head())

Rows with valid impression: 3337

   uid                                           findings
0    1  The cardiac silhouette and mediastinum size ar...
1    2  Borderline cardiomegaly. Midline sternotomy XX...
3    4  There are diffuse bilateral interstitial and a...
4    5  The cardiomediastinal silhouette and pulmonary...
5    6  Heart size and mediastinal contour are within ...

In [140]:
 proj_df["filename"] = proj_df["filename"].astype(str).str.strip()

uid_to_images = proj_df.groupby("uid")["filename"].apply(list).to_dict()

print("Number of uid entries with images:", len(uid_to_images))

sample_items = list(uid_to_images.items())[:5]
for uid, imgs in sample_items:
    print(uid, imgs)

Number of uid entries with images: 3851
1 ['1_IM-0001-4001.dcm.png', '1_IM-0001-3001.dcm.png']
2 ['2_IM-0652-1001.dcm.png', '2_IM-0652-2001.dcm.png']
3 ['3_IM-1384-1001.dcm.png', '3_IM-1384-2001.dcm.png']
4 ['4_IM-2050-1001.dcm.png', '4_IM-2050-2001.dcm.png']
5 ['5_IM-2117-1003002.dcm.png', '5_IM-2117-1004003.dcm.png']

In [141]:
reports_clean["image_filenames"] = reports_clean[ID_COL].map(uid_to_images)

merged_df = reports_clean.copy()
merged_df = merged_df[merged_df["image_filenames"].notna()]
merged_df = merged_df[merged_df["image_filenames"].apply(lambda x: isinstance(x, list) and len(x) > 0)]

print("Rows after merging with images:", len(merged_df))
display(merged_df[[ID_COL, TARGET_COL, "image_filenames"]].head())

Rows after merging with images: 3337

,uid,findings,image_filenames
0,1,The cardiac silhouette and mediastinum size ar...,"[1_IM-0001-4001.dcm.png, 1_IM-0001-3001.dcm.png]"
1,2,Borderline cardiomegaly. Midline sternotomy XX...,"[2_IM-0652-1001.dcm.png, 2_IM-0652-2001.dcm.png]"
3,4,There are diffuse bilateral interstitial and a...,"[4_IM-2050-1001.dcm.png, 4_IM-2050-2001.dcm.png]"
4,5,The cardiomediastinal silhouette and pulmonary...,"[5_IM-2117-1003002.dcm.png, 5_IM-2117-1004003...."
5,6,Heart size and mediastinal contour are within ...,"[6_IM-2192-1001.dcm.png, 6_IM-2192-2001.dcm.png]"

In [142]:
from pathlib import Path

images_dst = Path("/home/jupyter-st126671/data/iu_xray/images")
existing_images = {p.name for p in images_dst.iterdir() if p.is_file()}

def keep_existing(img_list):
    return [img for img in img_list if img in existing_images]

merged_df["image_filenames"] = merged_df["image_filenames"].apply(keep_existing)
merged_df = merged_df[merged_df["image_filenames"].apply(len) > 0]

print("Rows after checking actual image files:", len(merged_df))
display(merged_df[[ID_COL, TARGET_COL, "image_filenames"]].head())

Rows after checking actual image files: 3337

,uid,findings,image_filenames
0,1,The cardiac silhouette and mediastinum size ar...,"[1_IM-0001-4001.dcm.png, 1_IM-0001-3001.dcm.png]"
1,2,Borderline cardiomegaly. Midline sternotomy XX...,"[2_IM-0652-1001.dcm.png, 2_IM-0652-2001.dcm.png]"
3,4,There are diffuse bilateral interstitial and a...,"[4_IM-2050-1001.dcm.png, 4_IM-2050-2001.dcm.png]"
4,5,The cardiomediastinal silhouette and pulmonary...,"[5_IM-2117-1003002.dcm.png, 5_IM-2117-1004003...."
5,6,Heart size and mediastinal contour are within ...,"[6_IM-2192-1001.dcm.png, 6_IM-2192-2001.dcm.png]"

In [143]:
# =========================
# HYBRID RAG CONFIG
# =========================
import os
import json
import ast
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

R2GEN_ROOT = Path("/content/R2Gen")
DATA_ROOT = R2GEN_ROOT / "data" / "iu_xray"

TARGET_COL = "findings_clean"
TOP_K = 3
print("R2GEN_ROOT:", R2GEN_ROOT)
print("DATA_ROOT:", DATA_ROOT)
print("TARGET_COL:", TARGET_COL)
print("TOP_K:", TOP_K)

R2GEN_ROOT: /content/R2Gen
DATA_ROOT: /content/R2Gen/data/iu_xray
TARGET_COL: findings_clean
TOP_K: 3

In [144]:
from pathlib import Path

print("Current working directory:", Path.cwd())

print("\nLooking for train.csv, val.csv, test.csv, and problem_label_map.json...\n")
targets = {"train.csv", "val.csv", "test.csv", "problem_label_map.json"}

for p in Path.cwd().rglob("*"):
    if p.name in targets:
        print(p)

Current working directory: /home/jupyter-st126671/R2Gen/R2Gen

Looking for train.csv, val.csv, test.csv, and problem_label_map.json...

In [145]:
import pandas as pd
import json
from pathlib import Path

base = Path("/home/jupyter-st126671")
# or simply: base = Path.cwd()

train_df = pd.read_csv(base / "train.csv")
val_df = pd.read_csv(base / "val.csv")
test_df = pd.read_csv(base / "test.csv")

with open(base / "problem_label_map.json", "r", encoding="utf-8") as f:
    label_map = json.load(f)

print("train:", train_df.shape)
print("val:", val_df.shape)
print("test:", test_df.shape)
print("num labels:", len(label_map))
print("train columns:", train_df.columns.tolist())

train: (2060, 21)
val: (441, 21)
test: (442, 21)
num labels: 113
train columns: ['uid', 'mesh', 'problems', 'image', 'indication', 'comparison', 'findings', 'impression', 'mesh_clean', 'problems_clean', 'image_clean', 'indication_clean', 'comparison_clean', 'findings_clean', 'impression_clean', 'problems_list', 'num_problems', 'frontal_filename', 'frontal_path', 'lateral_filename', 'lateral_path']

In [146]:
from pathlib import Path

img_dir = Path("/home/jupyter-st126671/data/iu_xray/images")
existing_images = {p.name for p in img_dir.iterdir() if p.is_file()}

def has_both_images(row):
    f_ok = str(row["frontal_filename"]) in existing_images
    l_ok = str(row["lateral_filename"]) in existing_images
    return f_ok and l_ok

print("Before filtering:")
print("train:", len(train_df))
print("val:", len(val_df))
print("test:", len(test_df))

train_df = train_df[train_df.apply(has_both_images, axis=1)].reset_index(drop=True)
val_df = val_df[val_df.apply(has_both_images, axis=1)].reset_index(drop=True)
test_df = test_df[test_df.apply(has_both_images, axis=1)].reset_index(drop=True)

print("\nAfter filtering missing images:")
print("train:", len(train_df))
print("val:", len(val_df))
print("test:", len(test_df))

Before filtering:
train: 2060
val: 441
test: 442

After filtering missing images:
train: 2059
val: 440
test: 442

In [147]:
# =========================
# PROBLEM LABEL ENCODING
# =========================
def parse_problem_list(x):
    if pd.isna(x):
        return []
    if isinstance(x, list):
        return [str(v).strip().lower() for v in x if str(v).strip()]

    text = str(x).strip()

    try:
        parsed = ast.literal_eval(text)
        if isinstance(parsed, list):
            return [str(v).strip().lower() for v in parsed if str(v).strip()]
    except Exception:
        pass

    if ";" in text:
        return [p.strip().lower() for p in text.split(";") if p.strip()]
    if "," in text:
        return [p.strip().lower() for p in text.split(",") if p.strip()]

    return [text.lower()] if text else []

def encode_problem_vector(problem_list, label_map):
    vec = np.zeros(len(label_map), dtype=np.float32)
    for p in problem_list:
        if p in label_map:
            vec[label_map[p]] = 1.0
    return vec

for df in [train_df, val_df, test_df]:
    df["problem_list_parsed"] = df["problems_list"].apply(parse_problem_list)
    df["problem_vector"] = df["problem_list_parsed"].apply(lambda x: encode_problem_vector(x, label_map))

print(train_df[["problems_list", "problem_list_parsed"]].head())
print("problem_vector shape:", train_df["problem_vector"].iloc[0].shape)

                                   problems_list  \
0                        ['calcified granuloma']
1                                     ['normal']
2                                  ['scoliosis']
3                                     ['normal']
4  ['calcified granuloma', 'thoracic vertebrae']

                         problem_list_parsed
0                      [calcified granuloma]
1                                   [normal]
2                                [scoliosis]
3                                   [normal]
4  [calcified granuloma, thoracic vertebrae]
problem_vector shape: (113,)

In [148]:
# =========================
# RETRIEVAL BANK
# =========================
train_texts = train_df[TARGET_COL].fillna("").astype(str).tolist()
tfidf = TfidfVectorizer(max_features=5000)
train_text_matrix = tfidf.fit_transform(train_texts)
train_problem_matrix = np.vstack(train_df["problem_vector"].values)

print("TF-IDF matrix shape:", train_text_matrix.shape)
print("Problem matrix shape:", train_problem_matrix.shape)

TF-IDF matrix shape: (2059, 1352)
Problem matrix shape: (2059, 113)

In [149]:
# =========================
# RETRIEVAL FUNCTION
# =========================
def retrieve_similar_cases_from_row(row, top_k=3, w_text=0.5, w_problem=0.5):
    query_prob = row["problem_vector"].reshape(1, -1)
    prob_scores = cosine_similarity(query_prob, train_problem_matrix)[0]

    query_text = str(row[TARGET_COL]) if TARGET_COL in row else ""
    query_text_vec = tfidf.transform([query_text])
    text_scores = cosine_similarity(query_text_vec, train_text_matrix)[0]

    scores = (w_text * text_scores) + (w_problem * prob_scores)

    same_ids = train_df.index[train_df["uid"] == row["uid"]].tolist()
    for idx in same_ids:
        scores[idx] = -1

    top_idx = np.argsort(scores)[-top_k:][::-1]
    retrieved = train_df.iloc[top_idx][["uid", TARGET_COL, "problem_list_parsed"]].copy()
    retrieved["score"] = scores[top_idx]
    return retrieved

display(retrieve_similar_cases_from_row(val_df.iloc[0], top_k=TOP_K))

,uid,findings_clean,problem_list_parsed,score
1963,84,there are low lung volumes with bronchovascula...,"[lung, markings]",0.811580
1475,674,there are low lung volumes. there is bronchova...,"[lung, markings]",0.685242
1060,3299,the cardiac silhouette and mediastinal contour...,"[lung, markings]",0.655980

In [150]:
TARGET_COL = "findings_clean"

In [152]:
import pandas as pd
import json
import ast
import numpy as np
from pathlib import Path
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from pathlib import Path

BASE = Path("/home/jupyter-st126671/data/iu_xray")
IMG_DIR = BASE / "images"
ANN_PATH = BASE / "annotation_hybrid.json"

train_df = pd.read_csv("/home/jupyter-st126671/train.csv")
val_df = pd.read_csv("/home/jupyter-st126671/val.csv")
test_df = pd.read_csv("/home/jupyter-st126671/test.csv")

with open("/home/jupyter-st126671/problem_label_map.json", "r", encoding="utf-8") as f:
    label_map = json.load(f)

existing_images = {p.name for p in IMG_DIR.iterdir() if p.is_file()}

def has_both_images(row):
    f_ok = str(row["frontal_filename"]) in existing_images
    l_ok = str(row["lateral_filename"]) in existing_images
    return f_ok and l_ok

print("Before filtering")
print("train:", len(train_df))
print("val:", len(val_df))
print("test:", len(test_df))

train_df = train_df[train_df.apply(has_both_images, axis=1)].reset_index(drop=True)
val_df = val_df[val_df.apply(has_both_images, axis=1)].reset_index(drop=True)
test_df = test_df[test_df.apply(has_both_images, axis=1)].reset_index(drop=True)

print("\nAfter filtering")
print("train:", len(train_df))
print("val:", len(val_df))
print("test:", len(test_df))

def parse_problem_list(x):
    if pd.isna(x):
        return []
    if isinstance(x, list):
        return [str(v).strip().lower() for v in x if str(v).strip()]

    text = str(x).strip()

    try:
        parsed = ast.literal_eval(text)
        if isinstance(parsed, list):
            return [str(v).strip().lower() for v in parsed if str(v).strip()]
    except Exception:
        pass

    if ";" in text:
        return [p.strip().lower() for p in text.split(";") if p.strip()]
    if "," in text:
        return [p.strip().lower() for p in text.split(",") if p.strip()]

    return [text.lower()] if text else []

def encode_problem_vector(problem_list, label_map):
    vec = np.zeros(len(label_map), dtype=np.float32)
    for p in problem_list:
        if p in label_map:
            vec[label_map[p]] = 1.0
    return vec

for df in [train_df, val_df, test_df]:
    df["problem_list_parsed"] = df["problems_list"].apply(parse_problem_list)
    df["problem_vector"] = df["problem_list_parsed"].apply(lambda x: encode_problem_vector(x, label_map))

TARGET_COL = "findings_clean"
TOP_K = 3

train_texts = train_df[TARGET_COL].fillna("").astype(str).tolist()
tfidf = TfidfVectorizer(max_features=5000)
train_text_matrix = tfidf.fit_transform(train_texts)
train_problem_matrix = np.vstack(train_df["problem_vector"].values)

def retrieve_similar_cases_from_row(row, top_k=3, w_text=0.5, w_problem=0.5):
    query_prob = row["problem_vector"].reshape(1, -1)
    prob_scores = cosine_similarity(query_prob, train_problem_matrix)[0]

    query_text = str(row[TARGET_COL]) if TARGET_COL in row else ""
    query_text_vec = tfidf.transform([query_text])
    text_scores = cosine_similarity(query_text_vec, train_text_matrix)[0]

    scores = (w_text * text_scores) + (w_problem * prob_scores)

    same_ids = train_df.index[train_df["uid"] == row["uid"]].tolist()
    for idx in same_ids:
        scores[idx] = -1

    top_idx = np.argsort(scores)[-top_k:][::-1]
    retrieved = train_df.iloc[top_idx][["uid", TARGET_COL, "problem_list_parsed"]].copy()
    retrieved["score"] = scores[top_idx]
    return retrieved

def add_retrieval_context(df_split, top_k=3):
    enriched = []
    for _, row in df_split.iterrows():
        retrieved = retrieve_similar_cases_from_row(row, top_k=top_k)

        problem_vector = row["problem_vector"]
        if hasattr(problem_vector, "tolist"):
            problem_vector = problem_vector.tolist()

        example = {
            "id": str(row["uid"]),
            "image_path": [str(row["frontal_filename"]), str(row["lateral_filename"])],
            "report": str(row[TARGET_COL]).strip(),
            "problem_vector": problem_vector,
            "problem_list": row["problem_list_parsed"],
            "retrieved_reports": retrieved[TARGET_COL].astype(str).tolist(),
            "retrieved_problem_lists": retrieved["problem_list_parsed"].tolist(),
            "retrieved_scores": retrieved["score"].tolist()
        }
        enriched.append(example)
    return enriched

annotation_hybrid = {
    "train": add_retrieval_context(train_df, top_k=TOP_K),
    "val": add_retrieval_context(val_df, top_k=TOP_K),
    "test": add_retrieval_context(test_df, top_k=TOP_K),
}

with open(ANN_PATH, "w", encoding="utf-8") as f:
    json.dump(annotation_hybrid, f, indent=2, ensure_ascii=False)

print("Saved cleaned annotation to:", ANN_PATH)

Before filtering
train: 2060
val: 441
test: 442

After filtering
train: 2059
val: 440
test: 442
Saved cleaned annotation to: /home/jupyter-st126671/data/iu_xray/annotation_hybrid.json

In [155]:
!pwd
!ls /home/jupyter-st126671
!ls /home/jupyter-st126671/R2Gen
!ls /home/jupyter-st126671/data
!ls /home/jupyter-st126671/data/iu_xray

/home/jupyter-st126671/R2Gen/R2Gen
 data			  R2Gen				 train.csv
'Hybrid RAG.ipynb'	  R2Gen_A0.ipynb		 Untitled.ipynb
 master_dataset.csv	  R2Gen_HybridRAG_edited.ipynb	 val.csv
 problem_label_map.json   test.csv
data	 models   pycocoevalcap  README.md  run_iu_xray.sh
main.py  modules  R2Gen		 results    run_mimic_cxr.sh
iu_xray
annotation_hybrid.json	images

In [157]:
for file in [
    "/home/jupyter-st126671/R2Gen/modules/dataloaders.py",
    "/home/jupyter-st126671/R2Gen/modules/datasets.py",
    "/home/jupyter-st126671/R2Gen/modules/tokenizers.py",
]:
    print(f"\n===== {file} =====")
    try:
        with open(file, "r", encoding="utf-8") as f:
            lines = f.readlines()
        for i, line in enumerate(lines[:220], start=1):
            print(f"{i:4d}: {line.rstrip()}")
    except Exception as e:
        print("Could not read:", e)

===== /home/jupyter-st126671/R2Gen/modules/dataloaders.py =====
   1: import torch
   2: import numpy as np
   3: from torchvision import transforms
   4: from torch.utils.data import DataLoader
   5: from .datasets import IuxrayMultiImageDataset, MimiccxrSingleImageDataset
   6:
   7:
   8: class R2DataLoader(DataLoader):
   9:     def __init__(self, args, tokenizer, split, shuffle):
  10:         self.args = args
  11:         self.dataset_name = args.dataset_name
  12:         self.batch_size = args.batch_size
  13:         self.shuffle = shuffle
  14:         self.num_workers = args.num_workers
  15:         self.tokenizer = tokenizer
  16:         self.split = split
  17:
  18:         if split == 'train':
  19:             self.transform = transforms.Compose([
  20:                 transforms.Resize(256),
  21:                 transforms.RandomCrop(224),
  22:                 transforms.RandomHorizontalFlip(),
  23:                 transforms.ToTensor(),
  24:                 transforms.Normalize((0.485, 0.456, 0.406),
  25:                                      (0.229, 0.224, 0.225))])
  26:         else:
  27:             self.transform = transforms.Compose([
  28:                 transforms.Resize((224, 224)),
  29:                 transforms.ToTensor(),
  30:                 transforms.Normalize((0.485, 0.456, 0.406),
  31:                                      (0.229, 0.224, 0.225))])
  32:
  33:         if self.dataset_name == 'iu_xray':
  34:             self.dataset = IuxrayMultiImageDataset(self.args, self.tokenizer, self.split, transform=self.transform)
  35:         else:
  36:             self.dataset = MimiccxrSingleImageDataset(self.args, self.tokenizer, self.split, transform=self.transform)
  37:
  38:         self.init_kwargs = {
  39:             'dataset': self.dataset,
  40:             'batch_size': self.batch_size,
  41:             'shuffle': self.shuffle,
  42:             'collate_fn': self.collate_fn,
  43:             'num_workers': self.num_workers
  44:         }
  45:         super().__init__(**self.init_kwargs)
  46:
  47:     @staticmethod
  48:     def collate_fn(data):
  49:         images_id, images, reports_ids, reports_masks, seq_lengths, problem_vectors, retrieved_reports_texts = zip(*data)
  50:         images = torch.stack(images, 0)
  51:         max_seq_length = max(seq_lengths)
  52:
  53:         targets = np.zeros((len(reports_ids), max_seq_length), dtype=int)
  54:         targets_masks = np.zeros((len(reports_ids), max_seq_length), dtype=int)
  55:
  56:         for i, report_ids in enumerate(reports_ids):
  57:             targets[i, :len(report_ids)] = report_ids
  58:
  59:         for i, report_masks in enumerate(reports_masks):
  60:             targets_masks[i, :len(report_masks)] = report_masks
  61:
  62:         problem_vectors = torch.tensor(np.array(problem_vectors), dtype=torch.float32)
  63:
  64:         return (
  65:             images_id,
  66:             images,
  67:             torch.LongTensor(targets),
  68:             torch.FloatTensor(targets_masks),
  69:             seq_lengths,
  70:             problem_vectors,
  71:             retrieved_reports_texts
  72:         )
  73:

===== /home/jupyter-st126671/R2Gen/modules/datasets.py =====
   1: import os
   2: import json
   3: import torch
   4: from PIL import Image
   5: from torch.utils.data import Dataset
   6: import numpy as np
   7:
   8:
   9: class BaseDataset(Dataset):
  10:     def __init__(self, args, tokenizer, split, transform=None):
  11:         self.image_dir = args.image_dir
  12:         self.ann_path = args.ann_path
  13:         self.max_seq_length = args.max_seq_length
  14:         self.split = split
  15:         self.tokenizer = tokenizer
  16:         self.transform = transform
  17:         self.ann = json.loads(open(self.ann_path, 'r').read())
  18:
  19:         self.examples = self.ann[self.split]
  20:         for i in range(len(self.examples)):
  21:             self.examples[i]['ids'] = tokenizer(self.examples[i]['report'])[:self.max_seq_length]
  22:             self.examples[i]['mask'] = [1] * len(self.examples[i]['ids'])
  23:
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)
  47:
  48:         retrieved_reports = example.get('retrieved_reports', [])
  49:         retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])
  50:         sample = (
  51:             image_id,
  52:             image,
  53:             report_ids,
  54:             report_masks,
  55:             seq_length,
  56:             problem_vector,
  57:             retrieved_reports_text
  58:         )
  59:         return sample
  60:
  61:
  62: class MimiccxrSingleImageDataset(BaseDataset):
  63:     def __getitem__(self, idx):
  64:         example = self.examples[idx]
  65:         image_id = example['id']
  66:         image_path = example['image_path']
  67:         image = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  68:         if self.transform is not None:
  69:             image = self.transform(image)
  70:         report_ids = example['ids']
  71:         report_masks = example['mask']
  72:         seq_length = len(report_ids)
  73:         sample = (image_id, image, report_ids, report_masks, seq_length)
  74:         return sample

===== /home/jupyter-st126671/R2Gen/modules/tokenizers.py =====
   1: import json
   2: import re
   3: from collections import Counter
   4:
   5:
   6: class Tokenizer(object):
   7:     def __init__(self, args):
   8:         self.ann_path = args.ann_path
   9:         self.threshold = args.threshold
  10:         self.dataset_name = args.dataset_name
  11:         if self.dataset_name == 'iu_xray':
  12:             self.clean_report = self.clean_report_iu_xray
  13:         else:
  14:             self.clean_report = self.clean_report_mimic_cxr
  15:         self.ann = json.loads(open(self.ann_path, 'r').read())
  16:         self.token2idx, self.idx2token = self.create_vocabulary()
  17:
  18:     def create_vocabulary(self):
  19:         total_tokens = []
  20:
  21:         for example in self.ann['train']:
  22:             tokens = self.clean_report(example['report']).split()
  23:             for token in tokens:
  24:                 total_tokens.append(token)
  25:
  26:         counter = Counter(total_tokens)
  27:         vocab = [k for k, v in counter.items() if v >= self.threshold] + ['<unk>']
  28:         vocab.sort()
  29:         token2idx, idx2token = {}, {}
  30:         for idx, token in enumerate(vocab):
  31:             token2idx[token] = idx + 1
  32:             idx2token[idx + 1] = token
  33:         return token2idx, idx2token
  34:
  35:     def clean_report_iu_xray(self, report):
  36:         report_cleaner = lambda t: t.replace('..', '.').replace('..', '.').replace('..', '.').replace('1. ', '') \
  37:             .replace('. 2. ', '. ').replace('. 3. ', '. ').replace('. 4. ', '. ').replace('. 5. ', '. ') \
  38:             .replace(' 2. ', '. ').replace(' 3. ', '. ').replace(' 4. ', '. ').replace(' 5. ', '. ') \
  39:             .strip().lower().split('. ')
  40:         sent_cleaner = lambda t: re.sub('[.,?;*!%^&_+():-\[\]{}]', '', t.replace('"', '').replace('/', '').
  41:                                         replace('\\', '').replace("'", '').strip().lower())
  42:         tokens = [sent_cleaner(sent) for sent in report_cleaner(report) if sent_cleaner(sent) != []]
  43:         report = ' . '.join(tokens) + ' .'
  44:         return report
  45:
  46:     def clean_report_mimic_cxr(self, report):
  47:         report_cleaner = lambda t: t.replace('\n', ' ').replace('__', '_').replace('__', '_').replace('__', '_') \
  48:             .replace('__', '_').replace('__', '_').replace('__', '_').replace('__', '_').replace('  ', ' ') \
  49:             .replace('  ', ' ').replace('  ', ' ').replace('  ', ' ').replace('  ', ' ').replace('  ', ' ') \
  50:             .replace('..', '.').replace('..', '.').replace('..', '.').replace('..', '.').replace('..', '.') \
  51:             .replace('..', '.').replace('..', '.').replace('..', '.').replace('1. ', '').replace('. 2. ', '. ') \
  52:             .replace('. 3. ', '. ').replace('. 4. ', '. ').replace('. 5. ', '. ').replace(' 2. ', '. ') \
  53:             .replace(' 3. ', '. ').replace(' 4. ', '. ').replace(' 5. ', '. ') \
  54:             .strip().lower().split('. ')
  55:         sent_cleaner = lambda t: re.sub('[.,?;*!%^&_+():-\[\]{}]', '', t.replace('"', '').replace('/', '')
  56:                                         .replace('\\', '').replace("'", '').strip().lower())
  57:         tokens = [sent_cleaner(sent) for sent in report_cleaner(report) if sent_cleaner(sent) != []]
  58:         report = ' . '.join(tokens) + ' .'
  59:         return report
  60:
  61:     def get_token_by_id(self, id):
  62:         return self.idx2token[id]
  63:
  64:     def get_id_by_token(self, token):
  65:         if token not in self.token2idx:
  66:             return self.token2idx['<unk>']
  67:         return self.token2idx[token]
  68:
  69:     def get_vocab_size(self):
  70:         return len(self.token2idx)
  71:
  72:     def __call__(self, report):
  73:         tokens = self.clean_report(report).split()
  74:         ids = []
  75:         for token in tokens:
  76:             ids.append(self.get_id_by_token(token))
  77:         ids = [0] + ids + [0]
  78:         return ids
  79:
  80:     def decode(self, ids):
  81:         txt = ''
  82:         for i, idx in enumerate(ids):
  83:             if idx > 0:
  84:                 if i >= 1:
  85:                     txt += ' '
  86:                 txt += self.idx2token[idx]
  87:             else:
  88:                 break
  89:         return txt
  90:
  91:     def decode_batch(self, ids_batch):
  92:         out = []
  93:         for ids in ids_batch:
  94:             out.append(self.decode(ids))
  95:         return out

In [158]:
import sys
from pathlib import Path
from argparse import Namespace

R2GEN_ROOT = Path("/home/jupyter-st126671/R2Gen")
ANN_PATH = Path("/home/jupyter-st126671/data/iu_xray/annotation_hybrid.json")
IMG_DIR = Path("/home/jupyter-st126671/data/iu_xray/images")

if str(R2GEN_ROOT) not in sys.path:
    sys.path.append(str(R2GEN_ROOT))

from modules.tokenizers import Tokenizer
from modules.dataloaders import R2DataLoader

args = Namespace(
    image_dir=str(IMG_DIR),
    ann_path=str(ANN_PATH),
    dataset_name="iu_xray",
    max_seq_length=60,
    threshold=3,
    num_workers=0,
    batch_size=2,
)

print("image_dir exists:", IMG_DIR.exists(), IMG_DIR)
print("ann_path exists:", ANN_PATH.exists(), ANN_PATH)

tokenizer = Tokenizer(args)
train_loader = R2DataLoader(args, tokenizer, split="train", shuffle=True)

batch = next(iter(train_loader))
print("Loaded one batch successfully.")
print(type(batch))
print(len(batch))

image_dir exists: True /home/jupyter-st126671/data/iu_xray/images
ann_path exists: True /home/jupyter-st126671/data/iu_xray/annotation_hybrid.json
Loaded one batch successfully.
<class 'tuple'>
4

In [159]:
import sys
sys.path.append("/home/jupyter-st126671/R2Gen")

from argparse import Namespace
from modules.tokenizers import Tokenizer
from modules.dataloaders import R2DataLoader

args = Namespace(
    image_dir="/home/jupyter-st126671/data/iu_xray/images",
    ann_path="/home/jupyter-st126671/data/iu_xray/annotation_hybrid.json",
    dataset_name="iu_xray",
    max_seq_length=60,
    threshold=3,
    num_workers=2,
    batch_size=2,
)

print("Building tokenizer...")
tokenizer = Tokenizer(args)
print("Tokenizer vocab size:", len(tokenizer.token2idx))

print("Building train loader...")
train_loader = R2DataLoader(args, tokenizer, split="train", shuffle=True)

batch = next(iter(train_loader))
print("Loaded one batch successfully.")
print(type(batch))
print(batch)

Building tokenizer...
Tokenizer vocab size: 739
Building train loader...
Loaded one batch successfully.
<class 'tuple'>
(('3590', '3993'), tensor([[[[[ 1.5810,  1.5810,  1.5810,  ...,  0.3823,  0.3994,  0.3994],
           [ 1.1187,  1.1358,  1.1529,  ..., -0.6109, -0.6109, -0.6281],
           [ 0.6734,  0.6734,  0.7248,  ..., -1.2959, -1.3130, -1.3302],
           ...,
           [ 1.6324,  1.6838,  1.7180,  ...,  1.4440,  1.3755,  1.2899],
           [ 1.6324,  1.7009,  1.7180,  ...,  1.4098,  1.3584,  1.2899],
           [ 1.6495,  1.7009,  1.7352,  ...,  1.3755,  1.3070,  1.2385]],

          [[ 1.7458,  1.7458,  1.7458,  ...,  0.5203,  0.5378,  0.5378],
           [ 1.2731,  1.2906,  1.3081,  ..., -0.4951, -0.4951, -0.5126],
           [ 0.8179,  0.8179,  0.8704,  ..., -1.1954, -1.2129, -1.2304],
           ...,
           [ 1.7983,  1.8508,  1.8859,  ...,  1.6057,  1.5357,  1.4482],
           [ 1.7983,  1.8683,  1.8859,  ...,  1.5707,  1.5182,  1.4482],
           [ 1.8158,  1.8683,  1.9034,  ...,  1.5357,  1.4657,  1.3957]],

          [[ 1.9603,  1.9603,  1.9603,  ...,  0.7402,  0.7576,  0.7576],
           [ 1.4897,  1.5071,  1.5245,  ..., -0.2707, -0.2707, -0.2881],
           [ 1.0365,  1.0365,  1.0888,  ..., -0.9678, -0.9853, -1.0027],
           ...,
           [ 2.0125,  2.0648,  2.0997,  ...,  1.8208,  1.7511,  1.6640],
           [ 2.0125,  2.0823,  2.0997,  ...,  1.7860,  1.7337,  1.6640],
           [ 2.0300,  2.0823,  2.1171,  ...,  1.7511,  1.6814,  1.6117]]],


         [[[-1.3302, -1.3302, -1.3302,  ...,  1.2214,  0.1254,  0.9817],
           [-1.3302, -1.3302, -1.3302,  ...,  1.1872,  0.6221,  0.3994],
           [-1.3302, -1.3302, -1.3302,  ..., -0.0116,  0.0056, -0.3712],
           ...,
           [-0.2684, -0.1143, -0.0116,  ..., -0.4739, -0.5253, -0.5767],
           [-0.4397, -0.1828, -0.0801,  ..., -0.4911, -0.5253, -0.5596],
           [-0.6452, -0.3369, -0.1486,  ..., -0.5082, -0.5424, -0.5767]],

          [[-1.2304, -1.2304, -1.2304,  ...,  1.3782,  0.2577,  1.1331],
           [-1.2304, -1.2304, -1.2304,  ...,  1.3431,  0.7654,  0.5378],
           [-1.2304, -1.2304, -1.2304,  ...,  0.1176,  0.1352, -0.2500],
           ...,
           [-0.1450,  0.0126,  0.1176,  ..., -0.3550, -0.4076, -0.4601],
           [-0.3200, -0.0574,  0.0476,  ..., -0.3725, -0.4076, -0.4426],
           [-0.5301, -0.2150, -0.0224,  ..., -0.3901, -0.4251, -0.4601]],

          [[-1.0027, -1.0027, -1.0027,  ...,  1.5942,  0.4788,  1.3502],
           [-1.0027, -1.0027, -1.0027,  ...,  1.5594,  0.9842,  0.7576],
           [-1.0027, -1.0027, -1.0027,  ...,  0.3393,  0.3568, -0.0267],
           ...,
           [ 0.0779,  0.2348,  0.3393,  ..., -0.1312, -0.1835, -0.2358],
           [-0.0964,  0.1651,  0.2696,  ..., -0.1487, -0.1835, -0.2184],
           [-0.3055,  0.0082,  0.1999,  ..., -0.1661, -0.2010, -0.2358]]]],



        [[[[-0.8849, -0.7993, -0.7650,  ...,  0.1426,  0.1254,  0.1254],
           [-0.7993, -0.7308, -0.6623,  ...,  0.1597,  0.1597,  0.1597],
           [-0.6965, -0.5424, -0.3541,  ...,  0.2111,  0.2282,  0.2111],
           ...,
           [-2.0152, -1.6042, -1.4329,  ...,  0.2453,  0.1768,  0.0912],
           [-1.9809, -1.4500, -1.2788,  ...,  0.3994,  0.3138,  0.2282],
           [-1.9467, -1.3130, -1.1247,  ...,  0.5878,  0.5022,  0.3994]],

          [[-0.7752, -0.6877, -0.6527,  ...,  0.2752,  0.2577,  0.2577],
           [-0.6877, -0.6176, -0.5476,  ...,  0.2927,  0.2927,  0.2927],
           [-0.5826, -0.4251, -0.2325,  ...,  0.3452,  0.3627,  0.3452],
           ...,
           [-1.9307, -1.5105, -1.3354,  ...,  0.3803,  0.3102,  0.2227],
           [-1.8957, -1.3529, -1.1779,  ...,  0.5378,  0.4503,  0.3627],
           [-1.8606, -1.2129, -1.0203,  ...,  0.7304,  0.6429,  0.5378]],

          [[-0.5495, -0.4624, -0.4275,  ...,  0.4962,  0.4788,  0.4788],
           [-0.4624, -0.3927, -0.3230,  ...,  0.5136,  0.5136,  0.5136],
           [-0.3578, -0.2010, -0.0092,  ...,  0.5659,  0.5834,  0.5659],
           ...,
           [-1.6999, -1.2816, -1.1073,  ...,  0.6008,  0.5311,  0.4439],
           [-1.6650, -1.1247, -0.9504,  ...,  0.7576,  0.6705,  0.5834],
           [-1.6302, -0.9853, -0.7936,  ...,  0.9494,  0.8622,  0.7576]]],


         [[[-1.9980, -1.7925, -1.7583,  ...,  1.0673,  0.9474,  0.8618],
           [-1.9980, -1.8097, -1.7925,  ...,  1.0673,  0.9817,  0.8961],
           [-2.0152, -1.8268, -1.8268,  ...,  1.0844,  1.0159,  0.9303],
           ...,
           [-0.8164, -0.7479, -0.6965,  ..., -1.8610, -1.9124, -1.9638],
           [-0.7993, -0.7308, -0.6623,  ..., -1.8610, -1.9124, -1.9638],
           [-0.7822, -0.7308, -0.6623,  ..., -1.8782, -1.9124, -1.9809]],

          [[-1.9132, -1.7031, -1.6681,  ...,  1.2206,  1.0980,  1.0105],
           [-1.9132, -1.7206, -1.7031,  ...,  1.2206,  1.1331,  1.0455],
           [-1.9307, -1.7381, -1.7381,  ...,  1.2381,  1.1681,  1.0805],
           ...,
           [-0.7052, -0.6352, -0.5826,  ..., -1.7731, -1.8256, -1.8782],
           [-0.6877, -0.6176, -0.5476,  ..., -1.7731, -1.8256, -1.8782],
           [-0.6702, -0.6176, -0.5476,  ..., -1.7906, -1.8256, -1.8957]],

          [[-1.6824, -1.4733, -1.4384,  ...,  1.4374,  1.3154,  1.2282],
           [-1.6824, -1.4907, -1.4733,  ...,  1.4374,  1.3502,  1.2631],
           [-1.6999, -1.5081, -1.5081,  ...,  1.4548,  1.3851,  1.2980],
           ...,
           [-0.4798, -0.4101, -0.3578,  ..., -1.5430, -1.5953, -1.6476],
           [-0.4624, -0.3927, -0.3230,  ..., -1.5430, -1.5953, -1.6476],
           [-0.4450, -0.3927, -0.3230,  ..., -1.5604, -1.5953, -1.6650]]]]]), tensor([[  0, 305, 611, 734, 442, 377, 627, 412,  46, 311, 171,   2, 436, 274,
          43, 167, 436, 187, 503, 229, 592,   2, 436, 698, 267, 457, 534, 228,
           2, 436, 509,   2,   0],
        [  0, 670, 305, 354, 420, 239,   2, 369, 306, 354, 232,   2, 671, 354,
         436,  26, 340, 465, 503, 229,   2, 670, 413, 354, 705,   2,   0,   0,
           0,   0,   0,   0,   0]]), tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.]]))

In [161]:
file_path = "/home/jupyter-st126671/R2Gen/modules/datasets.py"

with open(file_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

for i, line in enumerate(lines, start=1):
    if "class " in line or "__init__" in line or "__getitem__" in line or "image_path" in line or "report" in line or "ann_path" in line:
        start = max(1, i - 8)
        end = min(len(lines), i + 25)
        print(f"\n--- lines {start} to {end} ---")
        for j in range(start, end + 1):
            print(f"{j:4d}: {lines[j-1].rstrip()}")

--- lines 1 to 34 ---
   1: import os
   2: import json
   3: import torch
   4: from PIL import Image
   5: from torch.utils.data import Dataset
   6: import numpy as np
   7:
   8:
   9: class BaseDataset(Dataset):
  10:     def __init__(self, args, tokenizer, split, transform=None):
  11:         self.image_dir = args.image_dir
  12:         self.ann_path = args.ann_path
  13:         self.max_seq_length = args.max_seq_length
  14:         self.split = split
  15:         self.tokenizer = tokenizer
  16:         self.transform = transform
  17:         self.ann = json.loads(open(self.ann_path, 'r').read())
  18:
  19:         self.examples = self.ann[self.split]
  20:         for i in range(len(self.examples)):
  21:             self.examples[i]['ids'] = tokenizer(self.examples[i]['report'])[:self.max_seq_length]
  22:             self.examples[i]['mask'] = [1] * len(self.examples[i]['ids'])
  23:
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')

--- lines 2 to 35 ---
   2: import json
   3: import torch
   4: from PIL import Image
   5: from torch.utils.data import Dataset
   6: import numpy as np
   7:
   8:
   9: class BaseDataset(Dataset):
  10:     def __init__(self, args, tokenizer, split, transform=None):
  11:         self.image_dir = args.image_dir
  12:         self.ann_path = args.ann_path
  13:         self.max_seq_length = args.max_seq_length
  14:         self.split = split
  15:         self.tokenizer = tokenizer
  16:         self.transform = transform
  17:         self.ann = json.loads(open(self.ann_path, 'r').read())
  18:
  19:         self.examples = self.ann[self.split]
  20:         for i in range(len(self.examples)):
  21:             self.examples[i]['ids'] = tokenizer(self.examples[i]['report'])[:self.max_seq_length]
  22:             self.examples[i]['mask'] = [1] * len(self.examples[i]['ids'])
  23:
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:

--- lines 4 to 37 ---
   4: from PIL import Image
   5: from torch.utils.data import Dataset
   6: import numpy as np
   7:
   8:
   9: class BaseDataset(Dataset):
  10:     def __init__(self, args, tokenizer, split, transform=None):
  11:         self.image_dir = args.image_dir
  12:         self.ann_path = args.ann_path
  13:         self.max_seq_length = args.max_seq_length
  14:         self.split = split
  15:         self.tokenizer = tokenizer
  16:         self.transform = transform
  17:         self.ann = json.loads(open(self.ann_path, 'r').read())
  18:
  19:         self.examples = self.ann[self.split]
  20:         for i in range(len(self.examples)):
  21:             self.examples[i]['ids'] = tokenizer(self.examples[i]['report'])[:self.max_seq_length]
  22:             self.examples[i]['mask'] = [1] * len(self.examples[i]['ids'])
  23:
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)

--- lines 9 to 42 ---
   9: class BaseDataset(Dataset):
  10:     def __init__(self, args, tokenizer, split, transform=None):
  11:         self.image_dir = args.image_dir
  12:         self.ann_path = args.ann_path
  13:         self.max_seq_length = args.max_seq_length
  14:         self.split = split
  15:         self.tokenizer = tokenizer
  16:         self.transform = transform
  17:         self.ann = json.loads(open(self.ann_path, 'r').read())
  18:
  19:         self.examples = self.ann[self.split]
  20:         for i in range(len(self.examples)):
  21:             self.examples[i]['ids'] = tokenizer(self.examples[i]['report'])[:self.max_seq_length]
  22:             self.examples[i]['mask'] = [1] * len(self.examples[i]['ids'])
  23:
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:

--- lines 13 to 46 ---
  13:         self.max_seq_length = args.max_seq_length
  14:         self.split = split
  15:         self.tokenizer = tokenizer
  16:         self.transform = transform
  17:         self.ann = json.loads(open(self.ann_path, 'r').read())
  18:
  19:         self.examples = self.ann[self.split]
  20:         for i in range(len(self.examples)):
  21:             self.examples[i]['ids'] = tokenizer(self.examples[i]['report'])[:self.max_seq_length]
  22:             self.examples[i]['mask'] = [1] * len(self.examples[i]['ids'])
  23:
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)

--- lines 20 to 53 ---
  20:         for i in range(len(self.examples)):
  21:             self.examples[i]['ids'] = tokenizer(self.examples[i]['report'])[:self.max_seq_length]
  22:             self.examples[i]['mask'] = [1] * len(self.examples[i]['ids'])
  23:
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)
  47:
  48:         retrieved_reports = example.get('retrieved_reports', [])
  49:         retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])
  50:         sample = (
  51:             image_id,
  52:             image,
  53:             report_ids,

--- lines 21 to 54 ---
  21:             self.examples[i]['ids'] = tokenizer(self.examples[i]['report'])[:self.max_seq_length]
  22:             self.examples[i]['mask'] = [1] * len(self.examples[i]['ids'])
  23:
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)
  47:
  48:         retrieved_reports = example.get('retrieved_reports', [])
  49:         retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])
  50:         sample = (
  51:             image_id,
  52:             image,
  53:             report_ids,
  54:             report_masks,

--- lines 24 to 57 ---
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)
  47:
  48:         retrieved_reports = example.get('retrieved_reports', [])
  49:         retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])
  50:         sample = (
  51:             image_id,
  52:             image,
  53:             report_ids,
  54:             report_masks,
  55:             seq_length,
  56:             problem_vector,
  57:             retrieved_reports_text

--- lines 25 to 58 ---
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)
  47:
  48:         retrieved_reports = example.get('retrieved_reports', [])
  49:         retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])
  50:         sample = (
  51:             image_id,
  52:             image,
  53:             report_ids,
  54:             report_masks,
  55:             seq_length,
  56:             problem_vector,
  57:             retrieved_reports_text
  58:         )

--- lines 26 to 59 ---
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)
  47:
  48:         retrieved_reports = example.get('retrieved_reports', [])
  49:         retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])
  50:         sample = (
  51:             image_id,
  52:             image,
  53:             report_ids,
  54:             report_masks,
  55:             seq_length,
  56:             problem_vector,
  57:             retrieved_reports_text
  58:         )
  59:         return sample

--- lines 31 to 64 ---
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)
  47:
  48:         retrieved_reports = example.get('retrieved_reports', [])
  49:         retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])
  50:         sample = (
  51:             image_id,
  52:             image,
  53:             report_ids,
  54:             report_masks,
  55:             seq_length,
  56:             problem_vector,
  57:             retrieved_reports_text
  58:         )
  59:         return sample
  60:
  61:
  62: class MimiccxrSingleImageDataset(BaseDataset):
  63:     def __getitem__(self, idx):
  64:         example = self.examples[idx]

--- lines 32 to 65 ---
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)
  47:
  48:         retrieved_reports = example.get('retrieved_reports', [])
  49:         retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])
  50:         sample = (
  51:             image_id,
  52:             image,
  53:             report_ids,
  54:             report_masks,
  55:             seq_length,
  56:             problem_vector,
  57:             retrieved_reports_text
  58:         )
  59:         return sample
  60:
  61:
  62: class MimiccxrSingleImageDataset(BaseDataset):
  63:     def __getitem__(self, idx):
  64:         example = self.examples[idx]
  65:         image_id = example['id']

--- lines 33 to 66 ---
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)
  47:
  48:         retrieved_reports = example.get('retrieved_reports', [])
  49:         retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])
  50:         sample = (
  51:             image_id,
  52:             image,
  53:             report_ids,
  54:             report_masks,
  55:             seq_length,
  56:             problem_vector,
  57:             retrieved_reports_text
  58:         )
  59:         return sample
  60:
  61:
  62: class MimiccxrSingleImageDataset(BaseDataset):
  63:     def __getitem__(self, idx):
  64:         example = self.examples[idx]
  65:         image_id = example['id']
  66:         image_path = example['image_path']

--- lines 40 to 73 ---
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)
  47:
  48:         retrieved_reports = example.get('retrieved_reports', [])
  49:         retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])
  50:         sample = (

In [162]:
from pathlib import Path

print("Current working directory:", Path.cwd())
print("\nSearching for datasets.py...\n")

matches = list(Path.cwd().rglob("datasets.py"))

if matches:
    for i, p in enumerate(matches):
        print(i, p)
else:
    print("No datasets.py found under the current folder.")

Current working directory: /home/jupyter-st126671/R2Gen/R2Gen

Searching for datasets.py...

0 /home/jupyter-st126671/R2Gen/R2Gen/modules/datasets.py

In [163]:
from pathlib import Path

file_path = Path("/home/jupyter-st126671/R2Gen/modules/datasets.py")

with open(file_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

keywords = [
    "class BaseDataset",
    "def __init__",
    "json.load",
    "self.examples",
    "tokenizer",
    "ids",
    "mask",
    "report"
]

for i, line in enumerate(lines, start=1):
    if any(k in line for k in keywords):
        start = max(1, i - 10)
        end = min(len(lines), i + 35)
        print(f"\n--- lines {start} to {end} ---")
        for j in range(start, end + 1):
            print(f"{j:4d}: {lines[j-1].rstrip()}")

--- lines 1 to 44 ---
   1: import os
   2: import json
   3: import torch
   4: from PIL import Image
   5: from torch.utils.data import Dataset
   6: import numpy as np
   7:
   8:
   9: class BaseDataset(Dataset):
  10:     def __init__(self, args, tokenizer, split, transform=None):
  11:         self.image_dir = args.image_dir
  12:         self.ann_path = args.ann_path
  13:         self.max_seq_length = args.max_seq_length
  14:         self.split = split
  15:         self.tokenizer = tokenizer
  16:         self.transform = transform
  17:         self.ann = json.loads(open(self.ann_path, 'r').read())
  18:
  19:         self.examples = self.ann[self.split]
  20:         for i in range(len(self.examples)):
  21:             self.examples[i]['ids'] = tokenizer(self.examples[i]['report'])[:self.max_seq_length]
  22:             self.examples[i]['mask'] = [1] * len(self.examples[i]['ids'])
  23:
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS

--- lines 1 to 45 ---
   1: import os
   2: import json
   3: import torch
   4: from PIL import Image
   5: from torch.utils.data import Dataset
   6: import numpy as np
   7:
   8:
   9: class BaseDataset(Dataset):
  10:     def __init__(self, args, tokenizer, split, transform=None):
  11:         self.image_dir = args.image_dir
  12:         self.ann_path = args.ann_path
  13:         self.max_seq_length = args.max_seq_length
  14:         self.split = split
  15:         self.tokenizer = tokenizer
  16:         self.transform = transform
  17:         self.ann = json.loads(open(self.ann_path, 'r').read())
  18:
  19:         self.examples = self.ann[self.split]
  20:         for i in range(len(self.examples)):
  21:             self.examples[i]['ids'] = tokenizer(self.examples[i]['report'])[:self.max_seq_length]
  22:             self.examples[i]['mask'] = [1] * len(self.examples[i]['ids'])
  23:
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================

--- lines 5 to 50 ---
   5: from torch.utils.data import Dataset
   6: import numpy as np
   7:
   8:
   9: class BaseDataset(Dataset):
  10:     def __init__(self, args, tokenizer, split, transform=None):
  11:         self.image_dir = args.image_dir
  12:         self.ann_path = args.ann_path
  13:         self.max_seq_length = args.max_seq_length
  14:         self.split = split
  15:         self.tokenizer = tokenizer
  16:         self.transform = transform
  17:         self.ann = json.loads(open(self.ann_path, 'r').read())
  18:
  19:         self.examples = self.ann[self.split]
  20:         for i in range(len(self.examples)):
  21:             self.examples[i]['ids'] = tokenizer(self.examples[i]['report'])[:self.max_seq_length]
  22:             self.examples[i]['mask'] = [1] * len(self.examples[i]['ids'])
  23:
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)
  47:
  48:         retrieved_reports = example.get('retrieved_reports', [])
  49:         retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])
  50:         sample = (

--- lines 7 to 52 ---
   7:
   8:
   9: class BaseDataset(Dataset):
  10:     def __init__(self, args, tokenizer, split, transform=None):
  11:         self.image_dir = args.image_dir
  12:         self.ann_path = args.ann_path
  13:         self.max_seq_length = args.max_seq_length
  14:         self.split = split
  15:         self.tokenizer = tokenizer
  16:         self.transform = transform
  17:         self.ann = json.loads(open(self.ann_path, 'r').read())
  18:
  19:         self.examples = self.ann[self.split]
  20:         for i in range(len(self.examples)):
  21:             self.examples[i]['ids'] = tokenizer(self.examples[i]['report'])[:self.max_seq_length]
  22:             self.examples[i]['mask'] = [1] * len(self.examples[i]['ids'])
  23:
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)
  47:
  48:         retrieved_reports = example.get('retrieved_reports', [])
  49:         retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])
  50:         sample = (
  51:             image_id,
  52:             image,

--- lines 9 to 54 ---
   9: class BaseDataset(Dataset):
  10:     def __init__(self, args, tokenizer, split, transform=None):
  11:         self.image_dir = args.image_dir
  12:         self.ann_path = args.ann_path
  13:         self.max_seq_length = args.max_seq_length
  14:         self.split = split
  15:         self.tokenizer = tokenizer
  16:         self.transform = transform
  17:         self.ann = json.loads(open(self.ann_path, 'r').read())
  18:
  19:         self.examples = self.ann[self.split]
  20:         for i in range(len(self.examples)):
  21:             self.examples[i]['ids'] = tokenizer(self.examples[i]['report'])[:self.max_seq_length]
  22:             self.examples[i]['mask'] = [1] * len(self.examples[i]['ids'])
  23:
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)
  47:
  48:         retrieved_reports = example.get('retrieved_reports', [])
  49:         retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])
  50:         sample = (
  51:             image_id,
  52:             image,
  53:             report_ids,
  54:             report_masks,

--- lines 10 to 55 ---
  10:     def __init__(self, args, tokenizer, split, transform=None):
  11:         self.image_dir = args.image_dir
  12:         self.ann_path = args.ann_path
  13:         self.max_seq_length = args.max_seq_length
  14:         self.split = split
  15:         self.tokenizer = tokenizer
  16:         self.transform = transform
  17:         self.ann = json.loads(open(self.ann_path, 'r').read())
  18:
  19:         self.examples = self.ann[self.split]
  20:         for i in range(len(self.examples)):
  21:             self.examples[i]['ids'] = tokenizer(self.examples[i]['report'])[:self.max_seq_length]
  22:             self.examples[i]['mask'] = [1] * len(self.examples[i]['ids'])
  23:
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)
  47:
  48:         retrieved_reports = example.get('retrieved_reports', [])
  49:         retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])
  50:         sample = (
  51:             image_id,
  52:             image,
  53:             report_ids,
  54:             report_masks,
  55:             seq_length,

--- lines 11 to 56 ---
  11:         self.image_dir = args.image_dir
  12:         self.ann_path = args.ann_path
  13:         self.max_seq_length = args.max_seq_length
  14:         self.split = split
  15:         self.tokenizer = tokenizer
  16:         self.transform = transform
  17:         self.ann = json.loads(open(self.ann_path, 'r').read())
  18:
  19:         self.examples = self.ann[self.split]
  20:         for i in range(len(self.examples)):
  21:             self.examples[i]['ids'] = tokenizer(self.examples[i]['report'])[:self.max_seq_length]
  22:             self.examples[i]['mask'] = [1] * len(self.examples[i]['ids'])
  23:
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)
  47:
  48:         retrieved_reports = example.get('retrieved_reports', [])
  49:         retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])
  50:         sample = (
  51:             image_id,
  52:             image,
  53:             report_ids,
  54:             report_masks,
  55:             seq_length,
  56:             problem_vector,

--- lines 12 to 57 ---
  12:         self.ann_path = args.ann_path
  13:         self.max_seq_length = args.max_seq_length
  14:         self.split = split
  15:         self.tokenizer = tokenizer
  16:         self.transform = transform
  17:         self.ann = json.loads(open(self.ann_path, 'r').read())
  18:
  19:         self.examples = self.ann[self.split]
  20:         for i in range(len(self.examples)):
  21:             self.examples[i]['ids'] = tokenizer(self.examples[i]['report'])[:self.max_seq_length]
  22:             self.examples[i]['mask'] = [1] * len(self.examples[i]['ids'])
  23:
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)
  47:
  48:         retrieved_reports = example.get('retrieved_reports', [])
  49:         retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])
  50:         sample = (
  51:             image_id,
  52:             image,
  53:             report_ids,
  54:             report_masks,
  55:             seq_length,
  56:             problem_vector,
  57:             retrieved_reports_text

--- lines 15 to 60 ---
  15:         self.tokenizer = tokenizer
  16:         self.transform = transform
  17:         self.ann = json.loads(open(self.ann_path, 'r').read())
  18:
  19:         self.examples = self.ann[self.split]
  20:         for i in range(len(self.examples)):
  21:             self.examples[i]['ids'] = tokenizer(self.examples[i]['report'])[:self.max_seq_length]
  22:             self.examples[i]['mask'] = [1] * len(self.examples[i]['ids'])
  23:
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)
  47:
  48:         retrieved_reports = example.get('retrieved_reports', [])
  49:         retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])
  50:         sample = (
  51:             image_id,
  52:             image,
  53:             report_ids,
  54:             report_masks,
  55:             seq_length,
  56:             problem_vector,
  57:             retrieved_reports_text
  58:         )
  59:         return sample
  60:

--- lines 20 to 65 ---
  20:         for i in range(len(self.examples)):
  21:             self.examples[i]['ids'] = tokenizer(self.examples[i]['report'])[:self.max_seq_length]
  22:             self.examples[i]['mask'] = [1] * len(self.examples[i]['ids'])
  23:
  24:     def __len__(self):
  25:         return len(self.examples)
  26:
  27:
  28: class IuxrayMultiImageDataset(BaseDataset):
  29:     def __getitem__(self, idx):
  30:         example = self.examples[idx]
  31:         image_id = example['id']
  32:         image_path = example['image_path']
  33:         image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  34:         image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  35:         if self.transform is not None:
  36:             image_1 = self.transform(image_1)
  37:             image_2 = self.transform(image_2)
  38:         image = torch.stack((image_1, image_2), 0)
  39:         report_ids = example['ids']
  40:         report_masks = example['mask']
  41:         seq_length = len(report_ids)
  42:
  43:         # =========================
  44:         # HYBRID RAG EXTRA FIELDS
  45:         # =========================
  46:         problem_vector = np.array(example.get('problem_vector', []), dtype=np.float32)
  47:
  48:         retrieved_reports = example.get('retrieved_reports', [])
  49:         retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])
  50:         sample = (
  51:             image_id,
  52:             image,
  53:             report_ids,
  54:             report_masks,
  55:             seq_length,
  56:             problem_vector,
  57:             retrieved_reports_text
  58:         )
  59:         return sample
  60:
  61:
  62: class MimiccxrSingleImageDataset(BaseDataset):

In [164]:
import sys
from pathlib import Path
from argparse import Namespace

R2GEN_ROOT = Path("/home/jupyter-st126671/R2Gen")
ANN_PATH = Path("/home/jupyter-st126671/data/iu_xray/annotation_hybrid.json")
IMG_DIR = Path("/home/jupyter-st126671/data/iu_xray/images")

if str(R2GEN_ROOT) not in sys.path:
    sys.path.append(str(R2GEN_ROOT))

from modules.tokenizers import Tokenizer
from modules.dataloaders import R2DataLoader

args = Namespace(
    image_dir=str(IMG_DIR),
    ann_path=str(ANN_PATH),
    dataset_name="iu_xray",
    max_seq_length=60,
    threshold=3,
    num_workers=2,
    batch_size=2,
)

print("image_dir exists:", IMG_DIR.exists(), IMG_DIR)
print("ann_path exists:", ANN_PATH.exists(), ANN_PATH)

print("Building tokenizer...")
tokenizer = Tokenizer(args)
print("Tokenizer built.")
print("Vocab size:", len(tokenizer.token2idx))

print("\nBuilding train loader...")
train_loader = R2DataLoader(args, tokenizer, split="train", shuffle=True)

print("Fetching one batch...")
batch = next(iter(train_loader))

print("Batch loaded successfully.")
print("Batch type:", type(batch))
print("Batch length:", len(batch))

image_dir exists: True /home/jupyter-st126671/data/iu_xray/images
ann_path exists: True /home/jupyter-st126671/data/iu_xray/annotation_hybrid.json
Building tokenizer...
Tokenizer built.
Vocab size: 739

Building train loader...
Fetching one batch...
Batch loaded successfully.
Batch type: <class 'tuple'>
Batch length: 4

In [165]:
for i, item in enumerate(batch):
    print(f"\nItem {i}:")
    if hasattr(item, "shape"):
        print("shape:", item.shape)
    else:
        print(type(item))
        try:
            print(item[:2])
        except:
            print(item)

Item 0:
<class 'tuple'>
('3072', '337')

Item 1:
shape: torch.Size([2, 2, 3, 224, 224])

Item 2:
shape: torch.Size([2, 60])

Item 3:
shape: torch.Size([2, 60])

In [166]:
!cat /home/jupyter-st126671/R2Gen/run_iu_xray.sh

python main.py \
--image_dir data/iu_xray/images/ \
--ann_path data/iu_xray/annotation.json \
--dataset_name iu_xray \
--max_seq_length 60 \
--threshold 3 \
--batch_size 16 \
--epochs 100 \
--save_dir results/iu_xray \
--step_size 50 \
--gamma 0.1 \
--seed 9223

In [167]:
from pathlib import Path

for p in Path("/home/jupyter-st126671/R2Gen").rglob("trainer.py"):
    print(p)

/home/jupyter-st126671/R2Gen/modules/trainer.py
/home/jupyter-st126671/R2Gen/R2Gen/modules/trainer.py

In [168]:
from pathlib import Path

file_path = Path("/home/jupyter-st126671/R2Gen/modules/trainer.py")
text = file_path.read_text(encoding="utf-8")

text = text.replace(
    "record_table = record_table.append(self.best_record['val'], ignore_index=True)",
    "record_table = pd.concat([record_table, pd.DataFrame([self.best_record['val']])], ignore_index=True)"
)

text = text.replace(
    "record_table = record_table.append(self.best_record['test'], ignore_index=True)",
    "record_table = pd.concat([record_table, pd.DataFrame([self.best_record['test']])], ignore_index=True)"
)

file_path.write_text(text, encoding="utf-8")
print("Patched trainer.py")

Patched trainer.py

In [169]:
# =========================
# PATCH DATASET TO RETURN HYBRID FIELDS
# =========================
from pathlib import Path
import re

dataset_file = Path("/home/jupyter-st126671/R2Gen/modules/datasets.py")
text = dataset_file.read_text(encoding="utf-8")

if "retrieved_reports_text" not in text:
    pattern = r"return image_id,\s*image,\s*report_ids,\s*report_masks,\s*seq_length"
    repl = """# HYBRID RAG EXTRA FIELDS
        item = self.examples[idx]
        problem_vector = np.array(item.get('problem_vector', []), dtype=np.float32)
        retrieved_reports = item.get('retrieved_reports', [])
        retrieved_reports_text = " ".join([str(x) for x in retrieved_reports])

        return image_id, image, report_ids, report_masks, seq_length, problem_vector, retrieved_reports_text"""
    text_new, n = re.subn(pattern, repl, text)
    if n == 0:
        print("WARNING: Could not patch datasets.py automatically. Check __getitem__ return manually.")
    else:
        dataset_file.write_text(text_new, encoding="utf-8")
        print("Patched:", dataset_file)
else:
    print("datasets.py already patched")

datasets.py already patched

In [170]:
# =========================
# PATCH DATALOADER COLLATE
# =========================
from pathlib import Path

dataloader_file = Path("/home/jupyter-st126671/R2Gen/modules/dataloaders.py")
text = dataloader_file.read_text(encoding="utf-8")

if "problem_vectors" not in text:
    text = text.replace(
        "image_ids, images, reports_ids, reports_masks, seq_lengths = zip(*data)",
        "image_ids, images, reports_ids, reports_masks, seq_lengths, problem_vectors, retrieved_reports_texts = zip(*data)"
    )

    text = text.replace(
        "return image_ids, images, targets, targets_masks",
        "problem_vectors = torch.tensor(np.array(problem_vectors), dtype=torch.float32)\n    return image_ids, images, targets, targets_masks, problem_vectors, retrieved_reports_texts"
    )

    dataloader_file.write_text(text, encoding='utf-8')
    print("Patched:", dataloader_file)
else:
    print("dataloaders.py already patched")

dataloaders.py already patched

In [171]:
# =========================
# FUSION MODULE
# =========================
from pathlib import Path

fusion_file = Path("/home/jupyter-st126671/R2Gen/modules/hybrid_fusion.py")
fusion_code = """
import torch
import torch.nn as nn
import torch.nn.functional as F

class HybridFusion(nn.Module):
    def __init__(self, img_dim, problem_dim, text_dim, hidden_dim):
        super().__init__()
        self.problem_proj = nn.Linear(problem_dim, hidden_dim)
        self.text_proj = nn.Linear(text_dim, hidden_dim)
        self.img_proj = nn.Linear(img_dim, hidden_dim)
        self.attn = nn.Linear(hidden_dim * 3, 3)

    def forward(self, img_feat, problem_vec, retrieved_text_feat):
        img_h = self.img_proj(img_feat)
        prob_h = self.problem_proj(problem_vec)
        text_h = self.text_proj(retrieved_text_feat)

        combined = torch.cat([img_h, prob_h, text_h], dim=-1)
        weights = F.softmax(self.attn(combined), dim=-1)

        fused = (
            weights[:, 0:1] * img_h +
            weights[:, 1:2] * prob_h +
            weights[:, 2:3] * text_h
        )
        return fused, weights
"""
fusion_file.write_text(fusion_code, encoding="utf-8")
print("Created:", fusion_file)

Created: /home/jupyter-st126671/R2Gen/modules/hybrid_fusion.py

In [172]:
# =========================
# SIMPLE RETRIEVED TEXT FEATURE BUILDER
# =========================
from sklearn.decomposition import TruncatedSVD

TEXT_FEAT_DIM = 256
svd = TruncatedSVD(n_components=TEXT_FEAT_DIM, random_state=42)
train_text_dense = svd.fit_transform(train_text_matrix)

def retrieved_text_to_feature(text):
    vec = tfidf.transform([text])
    dense = svd.transform(vec)
    return dense[0].astype(np.float32)

print("Dense text feature dim:", train_text_dense.shape)

Dense text feature dim: (2059, 256)

In [173]:
# =========================
# PATCH MODEL FOR PROBLEMS + RETRIEVAL + FUSION
# =========================
from pathlib import Path

model_candidates = [
    Path("/home/jupyter-st126671/R2Gen/models/r2gen.py"),
    Path("/home/jupyter-st126671/R2Gen/models/r2gen_model.py"),
]
MODEL_FILE = None
for p in model_candidates:
    if p.exists():
        MODEL_FILE = p
        break

if MODEL_FILE is None:
    print("WARNING: Could not find model file automatically. Patch manually.")
else:
    model_text = MODEL_FILE.read_text(encoding="utf-8")

    if "HybridFusion" not in model_text:
        model_text = "from models.hybrid_fusion import HybridFusion\nimport torch.nn as nn\n" + model_text

    if "self.problem_dim = 113" not in model_text:
        model_text = model_text.replace(
            "super(R2GenModel, self).__init__()",
            "super(R2GenModel, self).__init__()\n        self.problem_dim = 113\n        self.text_dim = 256"
        )

    if "self.hybrid_fusion" not in model_text:
        model_text = model_text.replace(
            "self.encoder_decoder = EncoderDecoder(args, tokenizer)",
            """self.encoder_decoder = EncoderDecoder(args, tokenizer)
        self.retrieval_text_encoder = nn.Sequential(
            nn.Linear(self.text_dim, self.text_dim),
            nn.ReLU(),
            nn.Linear(self.text_dim, self.text_dim)
        )
        self.hybrid_fusion = HybridFusion(
            img_dim=args.d_vf,
            problem_dim=self.problem_dim,
            text_dim=self.text_dim,
            hidden_dim=args.d_vf
        )"""
        )

    MODEL_FILE.write_text(model_text, encoding="utf-8")
    print("Patched:", MODEL_FILE)

Patched: /home/jupyter-st126671/R2Gen/models/r2gen.py

In [174]:
# =========================
# PATCH TRAINER INPUTS
# =========================
from pathlib import Path

trainer_file = Path("/home/jupyter-st126671/R2Gen/modules/trainer.py")
trainer_text = trainer_file.read_text(encoding="utf-8")

trainer_text = trainer_text.replace(
    "for batch_idx, (images_id, images, reports_ids, reports_masks) in enumerate(self.train_dataloader):",
    "for batch_idx, (images_id, images, reports_ids, reports_masks, problem_vectors, retrieved_reports_texts) in enumerate(self.train_dataloader):"
)

trainer_text = trainer_text.replace(
    "images, reports_ids, reports_masks = images.to(self.device), reports_ids.to(self.device), reports_masks.to(self.device)",
    "images, reports_ids, reports_masks = images.to(self.device), reports_ids.to(self.device), reports_masks.to(self.device)\n            problem_vectors = problem_vectors.to(self.device)"
)

trainer_file.write_text(trainer_text, encoding="utf-8")
print("Patched:", trainer_file)

Patched: /home/jupyter-st126671/R2Gen/modules/trainer.py

In [175]:
# =========================
# HYBRID ANNOTATION SWITCH
# =========================
print("Use this annotation file for the proposed model:")
print("/content/R2Gen/data/iu_xray/annotation_hybrid.json")

Use this annotation file for the proposed model:
/content/R2Gen/data/iu_xray/annotation_hybrid.json

In [176]:
!grep -n "record_table = pd.concat\|append(" /home/jupyter-st126671/R2Gen/modules/trainer.py

111:        record_table = record_table.append(self.best_recorder['val'], ignore_index=True)
112:        record_table = record_table.append(self.best_recorder['test'], ignore_index=True)

In [177]:
from pathlib import Path

hybrid_file = Path("/home/jupyter-st126671/R2Gen/models/hybrid_fusion.py")

hybrid_code = """
import torch
import torch.nn as nn

class HybridFusion(nn.Module):
    def __init__(self, img_dim, problem_dim, text_dim, hidden_dim):
        super(HybridFusion, self).__init__()

        self.problem_proj = nn.Linear(problem_dim, hidden_dim)
        self.text_proj = nn.Linear(text_dim, hidden_dim)
        self.gate = nn.Linear(hidden_dim * 3, hidden_dim)
        self.out = nn.Linear(hidden_dim * 3, hidden_dim)
        self.activation = nn.ReLU()
        self.sigmoid = nn.Sigmoid()

    def forward(self, img_feat, problem_vector, text_feat):
        problem_feat = self.activation(self.problem_proj(problem_vector))
        text_feat = self.activation(self.text_proj(text_feat))

        combined = torch.cat([img_feat, problem_feat, text_feat], dim=-1)
        gate = self.sigmoid(self.gate(combined))
        fused = self.out(combined) * gate
        return fused
"""

hybrid_file.write_text(hybrid_code, encoding="utf-8")
print("Created:", hybrid_file)

Created: /home/jupyter-st126671/R2Gen/models/hybrid_fusion.py

In [178]:
from pathlib import Path
from PIL import Image

img_dir = Path("/home/jupyter-st126671/data/iu_xray/images")

bad_files = []
all_pngs = list(img_dir.glob("*.png"))

print("Checking:", len(all_pngs), "images")

for i, p in enumerate(all_pngs, 1):
    try:
        with Image.open(p) as im:
            im.verify()
    except Exception as e:
        bad_files.append((p.name, str(e)))

    if i % 500 == 0:
        print(f"Checked {i}/{len(all_pngs)}")

print("\nBad files found:", len(bad_files))
for name, err in bad_files[:20]:
    print(name, "->", err)

Checking: 7468 images
Checked 500/7468
Checked 1000/7468
Checked 1500/7468
Checked 2000/7468
Checked 2500/7468
Checked 3000/7468
Checked 3500/7468
Checked 4000/7468
Checked 4500/7468
Checked 5000/7468
Checked 5500/7468
Checked 6000/7468
Checked 6500/7468
Checked 7000/7468

Bad files found: 0

In [180]:
from pathlib import Path

img_dir = Path("/home/jupyter-st126671/data/iu_xray/images")

for name, _ in bad_files:
    p = img_dir / name
    if p.exists():
        p.unlink()

print("Removed bad files:", len(bad_files))

Removed bad files: 0

In [ ]:
%cd /home/jupyter-st126671/R2Gen

!python main.py \
  --image_dir /home/jupyter-st126671/data/iu_xray/images \
  --ann_path /home/jupyter-st126671/data/iu_xray/annotation_hybrid.json \
  --dataset_name iu_xray \
  --max_seq_length 40 \
  --threshold 3 \
  --batch_size 4 \
  --epochs 30 \
  --save_dir results/iu_xray_hybrid \
  --step_size 50 \
  --gamma 0.1 \
  --seed 9223

/home/jupyter-st126671/R2Gen

/opt/tljh/user/lib/python3.12/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

/home/jupyter-st126671/.local/lib/python3.12/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/jupyter-st126671/.local/lib/python3.12/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet101_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet101_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

In [189]:
for i in range(len(reports)):
    print("\nGROUND TRUTH:", ground_truths[i])
    print("PREDICTED   :", reports[i])
    print("=" * 100)

NameError: name 'reports' is not defined