In [1]:
!git clone https://github.com/cuhksz-nlp/R2Gen.git
%cd R2Gen

!pip install kagglehub
import kagglehub
path = kagglehub.dataset_download("raddar/chest-xrays-indiana-university")
print(path)

fatal: destination path 'R2Gen' already exists and is not an empty directory.
/home/jupyter-st126489/NLU/Project/Progress/Ablation/R2Gen/R2Gen

/opt/tljh/user/lib/python3.12/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kagglehub in /home/jupyter-st126489/.local/lib/python3.12/site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in /home/jupyter-st126489/.local/lib/python3.12/site-packages (from kagglehub) (0.1.16)
Requirement already satisfied: packaging in /home/jupyter-st126489/.local/lib/python3.12/site-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in /home/jupyter-st126489/.local/lib/python3.12/site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /opt/tljh/user/lib/python3.12/site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in /home/jupyter-st126489/.local/lib/python3.12/site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in /home/jupyter-st126489/.local/lib/python3.12/site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (6.33.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/tljh/user/lib/python3.12/site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/jupyter-st126489/.local/lib/python3.12/site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/tljh/user/lib/python3.12/site-packages (from requests->kagglehub) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/jupyter-st126489/.local/lib/python3.12/site-packages (from requests->kagglehub) (2026.2.25)
/home/jupyter-st126489/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2

In [2]:
import os
from pathlib import Path

root = Path(path)   # 'path' is from kagglehub.dataset_download(...)

print("Dataset root:", root)
print("\nTop-level files/folders:")
for p in sorted(root.iterdir()):
    print("-", p.name)

print("\nSample tree (2 levels):")
for p in sorted(root.rglob("*")):
    rel = p.relative_to(root)
    if len(rel.parts) <= 2:
        print(rel)

Dataset root: /home/jupyter-st126489/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2

Top-level files/folders:
- images
- indiana_projections.csv
- indiana_reports.csv

Sample tree (2 levels):
images
images/images_normalized
indiana_projections.csv
indiana_reports.csv

In [3]:
import pandas as pd

png_files = list(root.rglob("*.png"))
print("PNG files:", len(png_files))

PNG files: 7470

In [4]:
from pathlib import Path
import shutil

project_root = Path("R2GenCMN")
iu_root = project_root / "data" / "iu_xray"
images_dst = iu_root / "images"

images_dst.mkdir(parents=True, exist_ok=True)

print("Created:", iu_root)
print("Created:", images_dst)

Created: R2GenCMN/data/iu_xray
Created: R2GenCMN/data/iu_xray/images

In [5]:
from pathlib import Path
import shutil

src_exts = {".png", ".jpg", ".jpeg"}
image_files = [p for p in root.rglob("*") if p.suffix.lower() in src_exts]

print("Found images:", len(image_files))

copied = 0
for img in image_files:
    dst = images_dst / img.name
    if not dst.exists():
        shutil.copy2(img, dst)
        copied += 1

print("Copied images:", copied)
print("Total now in destination:", len(list(images_dst.glob("*"))))

Found images: 7470
Copied images: 0
Total now in destination: 7470

In [6]:
print("Example destination files:")
for i, p in enumerate(sorted(images_dst.iterdir())):
    print(p.name)
    if i == 9:
        break

Example destination files:
1000_IM-0003-1001.dcm.png
1000_IM-0003-2001.dcm.png
1000_IM-0003-3001.dcm.png
1001_IM-0004-1001.dcm.png
1001_IM-0004-1002.dcm.png
1002_IM-0004-1001.dcm.png
1002_IM-0004-2001.dcm.png
1003_IM-0005-2002.dcm.png
1004_IM-0005-1001.dcm.png
1004_IM-0005-2001.dcm.png

In [7]:
import pandas as pd

csv_files = list(root.rglob("*.csv"))
print("CSV files found:")
for i, f in enumerate(csv_files):
    print(i, f)

# Try reading each CSV briefly
for f in csv_files:
    print("\n---", f.name, "---")
    try:
        df = pd.read_csv(f)
        print("shape:", df.shape)
        print("columns:", list(df.columns))
        print(df.head(2))
    except Exception as e:
        print("Could not read:", e)

CSV files found:
0 /home/jupyter-st126489/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_reports.csv
1 /home/jupyter-st126489/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_projections.csv

--- indiana_reports.csv ---
shape: (3851, 8)
columns: ['uid', 'MeSH', 'Problems', 'image', 'indication', 'comparison', 'findings', 'impression']
   uid                                               MeSH  \
0    1                                             normal
1    2  Cardiomegaly/borderline;Pulmonary Artery/enlarged

                        Problems                                image  \
0                         normal            Xray Chest PA and Lateral
1  Cardiomegaly;Pulmonary Artery  Chest, 2 views, frontal and lateral

                 indication comparison  \
0          Positive TB test      None.
1  Preop bariatric surgery.      None.

                                            findings  \
0  The cardiac silhouette and mediastinum size ar...
1  Borderline cardiomegaly. Midline sternotomy XX...

                     impression
0          Normal chest x-XXXX.
1  No acute pulmonary findings.

--- indiana_projections.csv ---
shape: (7466, 3)
columns: ['uid', 'filename', 'projection']
   uid                filename projection
0    1  1_IM-0001-4001.dcm.png    Frontal
1    1  1_IM-0001-3001.dcm.png    Lateral

In [8]:
report_csv = None

for f in csv_files:
    if "report" in f.name.lower() or "indiana" in f.name.lower():
        report_csv = f
        break

print("Selected CSV:", report_csv)

df = pd.read_csv(report_csv)
print(df.columns.tolist())
print(df.head())

Selected CSV: /home/jupyter-st126489/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_reports.csv
['uid', 'MeSH', 'Problems', 'image', 'indication', 'comparison', 'findings', 'impression']
   uid                                               MeSH  \
0    1                                             normal
1    2  Cardiomegaly/borderline;Pulmonary Artery/enlarged
2    3                                             normal
3    4  Pulmonary Disease, Chronic Obstructive;Bullous...
4    5  Osteophyte/thoracic vertebrae/multiple/small;T...

                                            Problems  \
0                                             normal
1                      Cardiomegaly;Pulmonary Artery
2                                             normal
3  Pulmonary Disease, Chronic Obstructive;Bullous...
4                         Osteophyte;Thickening;Lung

                                               image  \
0                          Xray Chest PA and Lateral
1                Chest, 2 views, frontal and lateral
2                          Xray Chest PA and Lateral
3  PA and lateral views of the chest XXXX, XXXX a...
4                          Xray Chest PA and Lateral

                                          indication      comparison  \
0                                   Positive TB test           None.
1                           Preop bariatric surgery.           None.
2  rib pain after a XXXX, XXXX XXXX steps this XX...             NaN
3                      XXXX-year-old XXXX with XXXX.  None available
4                        Chest and nasal congestion.             NaN

                                            findings  \
0  The cardiac silhouette and mediastinum size ar...
1  Borderline cardiomegaly. Midline sternotomy XX...
2                                                NaN
3  There are diffuse bilateral interstitial and a...
4  The cardiomediastinal silhouette and pulmonary...

                                          impression
0                               Normal chest x-XXXX.
1                       No acute pulmonary findings.
2  No displaced rib fractures, pneumothorax, or p...
3  1. Bullous emphysema and interstitial fibrosis...
4              No acute cardiopulmonary abnormality.

In [9]:
import pandas as pd
from pathlib import Path

csv_files = list(Path(path).rglob("*.csv"))

print("CSV files found:")
for i, f in enumerate(csv_files):
    print(i, f)

# Pick the report CSV manually after seeing the list if needed
report_csv = csv_files[0]
df = pd.read_csv(report_csv)

print("\nSelected CSV:", report_csv)
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("\nHead:")
display(df.head())

CSV files found:
0 /home/jupyter-st126489/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_reports.csv
1 /home/jupyter-st126489/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_projections.csv

Selected CSV: /home/jupyter-st126489/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_reports.csv
Shape: (3851, 8)
Columns: ['uid', 'MeSH', 'Problems', 'image', 'indication', 'comparison', 'findings', 'impression']

Head:

,uid,MeSH,Problems,image,indication,comparison,findings,impression
0,1,normal,normal,Xray Chest PA and Lateral,Positive TB test,None.,The cardiac silhouette and mediastinum size ar...,Normal chest x-XXXX.
1,2,Cardiomegaly/borderline;Pulmonary Artery/enlarged,Cardiomegaly;Pulmonary Artery,"Chest, 2 views, frontal and lateral",Preop bariatric surgery.,None.,Borderline cardiomegaly. Midline sternotomy XX...,No acute pulmonary findings.
2,3,normal,normal,Xray Chest PA and Lateral,"rib pain after a XXXX, XXXX XXXX steps this XX...",NaN,NaN,"No displaced rib fractures, pneumothorax, or p..."
3,4,"Pulmonary Disease, Chronic Obstructive;Bullous...","Pulmonary Disease, Chronic Obstructive;Bullous...","PA and lateral views of the chest XXXX, XXXX a...",XXXX-year-old XXXX with XXXX.,None available,There are diffuse bilateral interstitial and a...,1. Bullous emphysema and interstitial fibrosis...
4,5,Osteophyte/thoracic vertebrae/multiple/small;T...,Osteophyte;Thickening;Lung,Xray Chest PA and Lateral,Chest and nasal congestion.,NaN,The cardiomediastinal silhouette and pulmonary...,No acute cardiopulmonary abnormality.

In [10]:
# Check missing values in likely important columns
candidate_cols = [c for c in df.columns if c.lower() in ["uid", "id", "findings", "impression", "image", "filename", "problems"]]
print("Candidate columns:", candidate_cols)

for c in candidate_cols:
    print(f"{c}: missing =", df[c].isna().sum())

Candidate columns: ['uid', 'Problems', 'image', 'findings', 'impression']
uid: missing = 0
Problems: missing = 0
image: missing = 0
findings: missing = 514
impression: missing = 31

In [11]:
import pandas as pd
from pathlib import Path

csv_files = list(Path(path).rglob("*.csv"))

print("CSV files found:")
for i, f in enumerate(csv_files):
    print(i, f)

# choose the correct CSV index if needed
report_csv = csv_files[0]
df = pd.read_csv(report_csv)

print("\nSelected CSV:", report_csv)
print("\nExact columns:")
for i, c in enumerate(df.columns):
    print(i, repr(c))

CSV files found:
0 /home/jupyter-st126489/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_reports.csv
1 /home/jupyter-st126489/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_projections.csv

Selected CSV: /home/jupyter-st126489/.cache/kagglehub/datasets/raddar/chest-xrays-indiana-university/versions/2/indiana_reports.csv

Exact columns:
0 'uid'
1 'MeSH'
2 'Problems'
3 'image'
4 'indication'
5 'comparison'
6 'findings'
7 'impression'

In [12]:
import pandas as pd
from pathlib import Path

reports_csv = Path("../data/indiana_reports.csv")
projections_csv = Path("../data/indiana_projections.csv")

reports_df = pd.read_csv(reports_csv)
proj_df = pd.read_csv(projections_csv)

reports_df.columns = [c.strip() for c in reports_df.columns]
proj_df.columns = [c.strip() for c in proj_df.columns]

print("Reports columns:")
for i, c in enumerate(reports_df.columns):
    print(i, repr(c))

print("\nProjections columns:")
for i, c in enumerate(proj_df.columns):
    print(i, repr(c))

print("\nReports head:")
display(reports_df.head())

print("\nProjections head:")
display(proj_df.head())

Reports columns:
0 'uid'
1 'MeSH'
2 'Problems'
3 'image'
4 'indication'
5 'comparison'
6 'findings'
7 'impression'

Projections columns:
0 'uid'
1 'filename'
2 'projection'

Reports head:

,uid,MeSH,Problems,image,indication,comparison,findings,impression
0,1,normal,normal,Xray Chest PA and Lateral,Positive TB test,None.,The cardiac silhouette and mediastinum size ar...,Normal chest x-XXXX.
1,2,Cardiomegaly/borderline;Pulmonary Artery/enlarged,Cardiomegaly;Pulmonary Artery,"Chest, 2 views, frontal and lateral",Preop bariatric surgery.,None.,Borderline cardiomegaly. Midline sternotomy XX...,No acute pulmonary findings.
2,3,normal,normal,Xray Chest PA and Lateral,"rib pain after a XXXX, XXXX XXXX steps this XX...",NaN,NaN,"No displaced rib fractures, pneumothorax, or p..."
3,4,"Pulmonary Disease, Chronic Obstructive;Bullous...","Pulmonary Disease, Chronic Obstructive;Bullous...","PA and lateral views of the chest XXXX, XXXX a...",XXXX-year-old XXXX with XXXX.,None available,There are diffuse bilateral interstitial and a...,1. Bullous emphysema and interstitial fibrosis...
4,5,Osteophyte/thoracic vertebrae/multiple/small;T...,Osteophyte;Thickening;Lung,Xray Chest PA and Lateral,Chest and nasal congestion.,NaN,The cardiomediastinal silhouette and pulmonary...,No acute cardiopulmonary abnormality.

Projections head:

   uid                filename projection
0    1  1_IM-0001-4001.dcm.png    Frontal
1    1  1_IM-0001-3001.dcm.png    Lateral
2    2  2_IM-0652-1001.dcm.png    Frontal
3    2  2_IM-0652-2001.dcm.png    Lateral
4    3  3_IM-1384-1001.dcm.png    Frontal

In [13]:
lower_map_reports = {c.lower(): c for c in reports_df.columns}

print(lower_map_reports)

ID_COL = lower_map_reports.get("uid")
TARGET_COL = lower_map_reports.get("impression")

print("ID_COL =", ID_COL)
print("TARGET_COL =", TARGET_COL)

{'uid': 'uid', 'mesh': 'MeSH', 'problems': 'Problems', 'image': 'image', 'indication': 'indication', 'comparison': 'comparison', 'findings': 'findings', 'impression': 'impression'}
ID_COL = uid
TARGET_COL = impression

In [14]:
reports_clean = reports_df.copy()

reports_clean = reports_clean[reports_clean[TARGET_COL].notna()]
reports_clean[TARGET_COL] = reports_clean[TARGET_COL].astype(str).str.strip()
reports_clean = reports_clean[reports_clean[TARGET_COL] != ""]

print("Rows with valid impression:", len(reports_clean))
display(reports_clean[[ID_COL, TARGET_COL]].head())

Rows with valid impression: 3820

   uid                                         impression
0    1                               Normal chest x-XXXX.
1    2                       No acute pulmonary findings.
2    3  No displaced rib fractures, pneumothorax, or p...
3    4  1. Bullous emphysema and interstitial fibrosis...
4    5              No acute cardiopulmonary abnormality.

In [15]:
 proj_df["filename"] = proj_df["filename"].astype(str).str.strip()

uid_to_images = proj_df.groupby("uid")["filename"].apply(list).to_dict()

print("Number of uid entries with images:", len(uid_to_images))

sample_items = list(uid_to_images.items())[:5]
for uid, imgs in sample_items:
    print(uid, imgs)

Number of uid entries with images: 3851
1 ['1_IM-0001-4001.dcm.png', '1_IM-0001-3001.dcm.png']
2 ['2_IM-0652-1001.dcm.png', '2_IM-0652-2001.dcm.png']
3 ['3_IM-1384-1001.dcm.png', '3_IM-1384-2001.dcm.png']
4 ['4_IM-2050-1001.dcm.png', '4_IM-2050-2001.dcm.png']
5 ['5_IM-2117-1003002.dcm.png', '5_IM-2117-1004003.dcm.png']

In [16]:
reports_clean["image_filenames"] = reports_clean[ID_COL].map(uid_to_images)

merged_df = reports_clean.copy()
merged_df = merged_df[merged_df["image_filenames"].notna()]
merged_df = merged_df[merged_df["image_filenames"].apply(lambda x: isinstance(x, list) and len(x) > 0)]

print("Rows after merging with images:", len(merged_df))
display(merged_df[[ID_COL, TARGET_COL, "image_filenames"]].head())

Rows after merging with images: 3820

,uid,impression,image_filenames
0,1,Normal chest x-XXXX.,"[1_IM-0001-4001.dcm.png, 1_IM-0001-3001.dcm.png]"
1,2,No acute pulmonary findings.,"[2_IM-0652-1001.dcm.png, 2_IM-0652-2001.dcm.png]"
2,3,"No displaced rib fractures, pneumothorax, or p...","[3_IM-1384-1001.dcm.png, 3_IM-1384-2001.dcm.png]"
3,4,1. Bullous emphysema and interstitial fibrosis...,"[4_IM-2050-1001.dcm.png, 4_IM-2050-2001.dcm.png]"
4,5,No acute cardiopulmonary abnormality.,"[5_IM-2117-1003002.dcm.png, 5_IM-2117-1004003...."

In [17]:
from pathlib import Path

images_dst = Path("R2GenCMN/data/iu_xray/images")
existing_images = set(p.name for p in images_dst.iterdir() if p.is_file())

def keep_existing(img_list):
    return [img for img in img_list if img in existing_images]

merged_df["image_filenames"] = merged_df["image_filenames"].apply(keep_existing)
merged_df = merged_df[merged_df["image_filenames"].apply(len) > 0]

print("Rows after checking actual image files:", len(merged_df))
display(merged_df[[ID_COL, TARGET_COL, "image_filenames"]].head())

Rows after checking actual image files: 3820

,uid,impression,image_filenames
0,1,Normal chest x-XXXX.,"[1_IM-0001-4001.dcm.png, 1_IM-0001-3001.dcm.png]"
1,2,No acute pulmonary findings.,"[2_IM-0652-1001.dcm.png, 2_IM-0652-2001.dcm.png]"
2,3,"No displaced rib fractures, pneumothorax, or p...","[3_IM-1384-1001.dcm.png, 3_IM-1384-2001.dcm.png]"
3,4,1. Bullous emphysema and interstitial fibrosis...,"[4_IM-2050-1001.dcm.png, 4_IM-2050-2001.dcm.png]"
4,5,No acute cardiopulmonary abnormality.,"[5_IM-2117-1003002.dcm.png, 5_IM-2117-1004003...."

In [18]:
from sklearn.model_selection import train_test_split

case_df = merged_df[[ID_COL, TARGET_COL, "image_filenames", "Problems"]].copy()
case_df = case_df.drop_duplicates(subset=[ID_COL]).reset_index(drop=True)

train_df, temp_df = train_test_split(case_df, test_size=0.30, random_state=42)
val_df, test_df = train_test_split(temp_df, test_size=2/3, random_state=42)

print("Train:", len(train_df))
print("Val:", len(val_df))
print("Test:", len(test_df))

Train: 2674
Val: 382
Test: 764

In [19]:
def make_examples(df_split):
    examples = []
    for _, row in df_split.iterrows():

        # 🔥 Extract Problems column
        problems = ""
        if "Problems" in row and not pd.isna(row["Problems"]):
            problems = str(row["Problems"])

        examples.append({
            "id": str(row[ID_COL]),
            "image_path": row["image_filenames"],
            "report": str(row[TARGET_COL]).strip(),
            "Problems": problems   # 🔥 ADD THIS LINE
        })

    return examples

annotation = {
    "train": make_examples(train_df),
    "val": make_examples(val_df),
    "test": make_examples(test_df),
}

print("Train example:")
print(annotation["train"][0])

Train example:
{'id': '1240', 'image_path': ['1240_IM-0162-4001.dcm.png', '1240_IM-0162-2001.dcm.png'], 'report': '1. Stable left lung consolidation, possibly infectious pneumonia and/or aspiration. Recommend followup radiographs after treatment to ensure complete resolution. 2. Stable mild residual medial right basilar airspace disease.', 'Problems': 'Tube, Inserted;Catheters, Indwelling;Consolidation;Airspace Disease;Atherosclerosis;Spine'}

In [20]:
import json
from pathlib import Path

ann_path = Path("../data/iu_xray/annotation.json")
ann_path.parent.mkdir(parents=True, exist_ok=True)

with open(ann_path, "w", encoding="utf-8") as f:
    json.dump(annotation, f, indent=2, ensure_ascii=False)

print("Saved annotation to:", ann_path)

Saved annotation to: ../data/iu_xray/annotation.json

In [21]:
with open("../data/iu_xray/annotation.json", "r", encoding="utf-8") as f:
    ann = json.load(f)

print("Keys:", ann.keys())
print("Train size:", len(ann["train"]))
print("Val size:", len(ann["val"]))
print("Test size:", len(ann["test"]))
print("\nSample entry:")
print(ann["train"][0])

Keys: dict_keys(['train', 'val', 'test'])
Train size: 2674
Val size: 382
Test size: 764

Sample entry:
{'id': '1240', 'image_path': ['1240_IM-0162-4001.dcm.png', '1240_IM-0162-2001.dcm.png'], 'report': '1. Stable left lung consolidation, possibly infectious pneumonia and/or aspiration. Recommend followup radiographs after treatment to ensure complete resolution. 2. Stable mild residual medial right basilar airspace disease.', 'Problems': 'Tube, Inserted;Catheters, Indwelling;Consolidation;Airspace Disease;Atherosclerosis;Spine'}

In [22]:
!grep -R "image_path\|report\|ann_path\|split\|json.load\|tokenizer" -n ../modules ../data ../main.py

../modules/datasets.py:12:    def __init__(self, args, tokenizer, split, transform=None):
../modules/datasets.py:15:        self.ann_path = args.ann_path
../modules/datasets.py:17:        self.split = split
../modules/datasets.py:18:        self.tokenizer = tokenizer
../modules/datasets.py:22:        with open(self.ann_path, 'r') as f:
../modules/datasets.py:23:            self.ann = json.load(f)
../modules/datasets.py:25:        # 🔥 Build label vocabulary from ALL splits
../modules/datasets.py:28:        # Current split data
../modules/datasets.py:29:        self.examples = self.ann[self.split]
../modules/datasets.py:31:        # Tokenize reports
../modules/datasets.py:33:            tokens = tokenizer(self.examples[i]['report'])
../modules/datasets.py:46:        for split in ann:  # train / val / test
../modules/datasets.py:47:            for sample in ann[split]:
../modules/datasets.py:50:                    items = [p.strip() for p in probs.split(',')]
../modules/datasets.py:63:            items = [p.strip() for p in probs.split(',')]
../modules/datasets.py:79:        image_path = example['image_path']
../modules/datasets.py:83:            image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
../modules/datasets.py:87:        if len(image_path) > 1:
../modules/datasets.py:89:                image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
../modules/datasets.py:104:        report_ids = example['ids']
../modules/datasets.py:105:        report_masks = example['mask']
../modules/datasets.py:106:        seq_length = len(report_ids)
../modules/datasets.py:112:        return image_id, image, problem_vec, report_ids, report_masks, seq_length
../modules/datasets.py:123:        image_path = example['image_path']
../modules/datasets.py:125:        image = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
../modules/datasets.py:130:        report_ids = example['ids']
../modules/datasets.py:131:        report_masks = example['mask']
../modules/datasets.py:132:        seq_length = len(report_ids)
../modules/datasets.py:138:        return image_id, image, problem_vec, report_ids, report_masks, seq_length
../modules/caption_model.py:135:        args = utils.split_tensors(group_size, args)  # For each arg, turn (Bbg)x... to (Bb)x(g)x...
../modules/encoder_decoder.py:283:        gates = torch.split(gates, split_size_or_sections=self.d_model, dim=2)
../modules/encoder_decoder.py:324:    def __init__(self, args, tokenizer):
../modules/encoder_decoder.py:325:        super(EncoderDecoder, self).__init__(args, tokenizer)
../modules/dataloaders.py:9:    def __init__(self, args, tokenizer, split, shuffle):
../modules/dataloaders.py:15:        self.tokenizer = tokenizer
../modules/dataloaders.py:16:        self.split = split
../modules/dataloaders.py:18:        if split == 'train':
../modules/dataloaders.py:34:            self.dataset = IuxrayMultiImageDataset(self.args, self.tokenizer, self.split, transform=self.transform)
../modules/dataloaders.py:36:            self.dataset = MimiccxrSingleImageDataset(self.args, self.tokenizer, self.split, transform=self.transform)
../modules/dataloaders.py:49:        images_id, images, reports_ids, reports_masks, seq_lengths = zip(*data)
../modules/dataloaders.py:53:        targets = np.zeros((len(reports_ids), max_seq_length), dtype=int)
../modules/dataloaders.py:54:        targets_masks = np.zeros((len(reports_ids), max_seq_length), dtype=int)
../modules/dataloaders.py:56:        for i, report_ids in enumerate(reports_ids):
../modules/dataloaders.py:57:            targets[i, :len(report_ids)] = report_ids
../modules/dataloaders.py:59:        for i, report_masks in enumerate(reports_masks):
../modules/dataloaders.py:60:            targets_masks[i, :len(report_masks)] = report_masks
../modules/att_model.py:37:    def __init__(self, args, tokenizer):
../modules/att_model.py:40:        self.tokenizer = tokenizer
../modules/att_model.py:41:        self.vocab_size = len(tokenizer.idx2token)
../modules/trainer.py:217:            images_id, images, problem_vec, reports_ids, reports_masks, seq_length = batch
../modules/trainer.py:221:            reports_ids = reports_ids.to(self.device)
../modules/trainer.py:222:            reports_masks = reports_masks.to(self.device)
../modules/trainer.py:224:            output = self.model(images, problem_vec, reports_ids, mode='train')
../modules/trainer.py:226:            loss = self.criterion(output, reports_ids, reports_masks)
../modules/trainer.py:242:                images_id, images, problem_vec, reports_ids, reports_masks, seq_length = batch
../modules/trainer.py:246:                reports_ids = reports_ids.to(self.device)
../modules/trainer.py:250:                reports = self.model.tokenizer.decode_batch(output.cpu().numpy())
../modules/trainer.py:251:                gts = self.model.tokenizer.decode_batch(reports_ids[:, 1:].cpu().numpy())
../modules/trainer.py:253:                val_res.extend(reports)
../modules/trainer.py:268:                images_id, images, problem_vec, reports_ids, reports_masks, seq_length = batch
../modules/trainer.py:272:                reports_ids = reports_ids.to(self.device)
../modules/trainer.py:276:                reports = self.model.tokenizer.decode_batch(output.cpu().numpy())
../modules/trainer.py:277:                gts = self.model.tokenizer.decode_batch(reports_ids[:, 1:].cpu().numpy())
../modules/trainer.py:279:                test_res.extend(reports)
../modules/utils.py:7:    pen_type, alpha = penalty_config.split('_')
../modules/utils.py:33:def split_tensors(n, x):
../modules/utils.py:38:        x = [split_tensors(n, _) for _ in x]
../modules/tokenizers.py:8:        self.ann_path = args.ann_path
../modules/tokenizers.py:12:            self.clean_report = self.clean_report_iu_xray
../modules/tokenizers.py:14:            self.clean_report = self.clean_report_mimic_cxr
../modules/tokenizers.py:15:        self.ann = json.loads(open(self.ann_path, 'r').read())
../modules/tokenizers.py:22:            tokens = self.clean_report(example['report']).split()
../modules/tokenizers.py:35:    def clean_report_iu_xray(self, report):
../modules/tokenizers.py:36:        report_cleaner = lambda t: t.replace('..', '.').replace('..', '.').replace('..', '.').replace('1. ', '') \
../modules/tokenizers.py:39:            .strip().lower().split('. ')
../modules/tokenizers.py:42:        tokens = [sent_cleaner(sent) for sent in report_cleaner(report) if sent_cleaner(sent) != []]
../modules/tokenizers.py:43:        report = ' . '.join(tokens) + ' .'
../modules/tokenizers.py:44:        return report
../modules/tokenizers.py:46:    def clean_report_mimic_cxr(self, report):
../modules/tokenizers.py:47:        report_cleaner = lambda t: t.replace('\n', ' ').replace('__', '_').replace('__', '_').replace('__', '_') \
../modules/tokenizers.py:54:            .strip().lower().split('. ')
../modules/tokenizers.py:57:        tokens = [sent_cleaner(sent) for sent in report_cleaner(report) if sent_cleaner(sent) != []]
../modules/tokenizers.py:58:        report = ' . '.join(tokens) + ' .'
../modules/tokenizers.py:59:        return report
../modules/tokenizers.py:72:    def __call__(self, report):
../modules/tokenizers.py:73:        tokens = self.clean_report(report).split()
../modules/.ipynb_checkpoints/datasets-checkpoint.py:12:    def __init__(self, args, tokenizer, split, transform=None):
../modules/.ipynb_checkpoints/datasets-checkpoint.py:15:        self.ann_path = args.ann_path
../modules/.ipynb_checkpoints/datasets-checkpoint.py:17:        self.split = split
../modules/.ipynb_checkpoints/datasets-checkpoint.py:18:        self.tokenizer = tokenizer
../modules/.ipynb_checkpoints/datasets-checkpoint.py:22:        with open(self.ann_path, 'r') as f:
../modules/.ipynb_checkpoints/datasets-checkpoint.py:23:            self.ann = json.load(f)
../modules/.ipynb_checkpoints/datasets-checkpoint.py:25:        # 🔥 Build label vocabulary from ALL splits
../modules/.ipynb_checkpoints/datasets-checkpoint.py:28:        # Current split data
../modules/.ipynb_checkpoints/datasets-checkpoint.py:29:        self.examples = self.ann[self.split]
../modules/.ipynb_checkpoints/datasets-checkpoint.py:31:        # Tokenize reports
../modules/.ipynb_checkpoints/datasets-checkpoint.py:33:            tokens = tokenizer(self.examples[i]['report'])
../modules/.ipynb_checkpoints/datasets-checkpoint.py:46:        for split in ann:  # train / val / test
../modules/.ipynb_checkpoints/datasets-checkpoint.py:47:            for sample in ann[split]:
../modules/.ipynb_checkpoints/datasets-checkpoint.py:50:                    items = [p.strip() for p in probs.split(',')]
../modules/.ipynb_checkpoints/datasets-checkpoint.py:63:            items = [p.strip() for p in probs.split(',')]
../modules/.ipynb_checkpoints/datasets-checkpoint.py:79:        image_path = example['image_path']
../modules/.ipynb_checkpoints/datasets-checkpoint.py:83:            image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
../modules/.ipynb_checkpoints/datasets-checkpoint.py:87:        if len(image_path) > 1:
../modules/.ipynb_checkpoints/datasets-checkpoint.py:89:                image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
../modules/.ipynb_checkpoints/datasets-checkpoint.py:104:        report_ids = example['ids']
../modules/.ipynb_checkpoints/datasets-checkpoint.py:105:        report_masks = example['mask']
../modules/.ipynb_checkpoints/datasets-checkpoint.py:106:        seq_length = len(report_ids)
../modules/.ipynb_checkpoints/datasets-checkpoint.py:112:        return image_id, image, problem_vec, report_ids, report_masks, seq_length
../modules/.ipynb_checkpoints/datasets-checkpoint.py:123:        image_path = example['image_path']
../modules/.ipynb_checkpoints/datasets-checkpoint.py:125:        image = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
../modules/.ipynb_checkpoints/datasets-checkpoint.py:130:        report_ids = example['ids']
../modules/.ipynb_checkpoints/datasets-checkpoint.py:131:        report_masks = example['mask']
../modules/.ipynb_checkpoints/datasets-checkpoint.py:132:        seq_length = len(report_ids)
../modules/.ipynb_checkpoints/datasets-checkpoint.py:138:        return image_id, image, problem_vec, report_ids, report_masks, seq_length
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:8:        self.ann_path = args.ann_path
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:12:            self.clean_report = self.clean_report_iu_xray
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:14:            self.clean_report = self.clean_report_mimic_cxr
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:15:        self.ann = json.loads(open(self.ann_path, 'r').read())
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:22:            tokens = self.clean_report(example['report']).split()
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:35:    def clean_report_iu_xray(self, report):
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:36:        report_cleaner = lambda t: t.replace('..', '.').replace('..', '.').replace('..', '.').replace('1. ', '') \
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:39:            .strip().lower().split('. ')
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:42:        tokens = [sent_cleaner(sent) for sent in report_cleaner(report) if sent_cleaner(sent) != []]
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:43:        report = ' . '.join(tokens) + ' .'
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:44:        return report
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:46:    def clean_report_mimic_cxr(self, report):
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:47:        report_cleaner = lambda t: t.replace('\n', ' ').replace('__', '_').replace('__', '_').replace('__', '_') \
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:54:            .strip().lower().split('. ')
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:57:        tokens = [sent_cleaner(sent) for sent in report_cleaner(report) if sent_cleaner(sent) != []]
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:58:        report = ' . '.join(tokens) + ' .'
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:59:        return report
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:72:    def __call__(self, report):
../modules/.ipynb_checkpoints/tokenizers-checkpoint.py:73:        tokens = self.clean_report(report).split()
../modules/.ipynb_checkpoints/dataloaders-checkpoint.py:9:    def __init__(self, args, tokenizer, split, shuffle):
../modules/.ipynb_checkpoints/dataloaders-checkpoint.py:15:        self.tokenizer = tokenizer
../modules/.ipynb_checkpoints/dataloaders-checkpoint.py:16:        self.split = split
../modules/.ipynb_checkpoints/dataloaders-checkpoint.py:18:        if split == 'train':
../modules/.ipynb_checkpoints/dataloaders-checkpoint.py:34:            self.dataset = IuxrayMultiImageDataset(self.args, self.tokenizer, self.split, transform=self.transform)
../modules/.ipynb_checkpoints/dataloaders-checkpoint.py:36:            self.dataset = MimiccxrSingleImageDataset(self.args, self.tokenizer, self.split, transform=self.transform)
../modules/.ipynb_checkpoints/dataloaders-checkpoint.py:49:        images_id, images, reports_ids, reports_masks, seq_lengths = zip(*data)
../modules/.ipynb_checkpoints/dataloaders-checkpoint.py:53:        targets = np.zeros((len(reports_ids), max_seq_length), dtype=int)
../modules/.ipynb_checkpoints/dataloaders-checkpoint.py:54:        targets_masks = np.zeros((len(reports_ids), max_seq_length), dtype=int)
../modules/.ipynb_checkpoints/dataloaders-checkpoint.py:56:        for i, report_ids in enumerate(reports_ids):
../modules/.ipynb_checkpoints/dataloaders-checkpoint.py:57:            targets[i, :len(report_ids)] = report_ids
../modules/.ipynb_checkpoints/dataloaders-checkpoint.py:59:        for i, report_masks in enumerate(reports_masks):
../modules/.ipynb_checkpoints/dataloaders-checkpoint.py:60:            targets_masks[i, :len(report_masks)] = report_masks
../modules/.ipynb_checkpoints/trainer-checkpoint.py:217:            images_id, images, problem_vec, reports_ids, reports_masks, seq_length = batch
../modules/.ipynb_checkpoints/trainer-checkpoint.py:221:            reports_ids = reports_ids.to(self.device)
../modules/.ipynb_checkpoints/trainer-checkpoint.py:222:            reports_masks = reports_masks.to(self.device)
../modules/.ipynb_checkpoints/trainer-checkpoint.py:224:            output = self.model(images, problem_vec, reports_ids, mode='train')
../modules/.ipynb_checkpoints/trainer-checkpoint.py:226:            loss = self.criterion(output, reports_ids, reports_masks)
../modules/.ipynb_checkpoints/trainer-checkpoint.py:242:                images_id, images, problem_vec, reports_ids, reports_masks, seq_length = batch
../modules/.ipynb_checkpoints/trainer-checkpoint.py:246:                reports_ids = reports_ids.to(self.device)
../modules/.ipynb_checkpoints/trainer-checkpoint.py:250:                reports = self.model.tokenizer.decode_batch(output.cpu().numpy())
../modules/.ipynb_checkpoints/trainer-checkpoint.py:251:                gts = self.model.tokenizer.decode_batch(reports_ids[:, 1:].cpu().numpy())
../modules/.ipynb_checkpoints/trainer-checkpoint.py:253:                val_res.extend(reports)
../modules/.ipynb_checkpoints/trainer-checkpoint.py:268:                images_id, images, problem_vec, reports_ids, reports_masks, seq_length = batch
../modules/.ipynb_checkpoints/trainer-checkpoint.py:272:                reports_ids = reports_ids.to(self.device)
../modules/.ipynb_checkpoints/trainer-checkpoint.py:276:                reports = self.model.tokenizer.decode_batch(output.cpu().numpy())
../modules/.ipynb_checkpoints/trainer-checkpoint.py:277:                gts = self.model.tokenizer.decode_batch(reports_ids[:, 1:].cpu().numpy())
../modules/.ipynb_checkpoints/trainer-checkpoint.py:279:                test_res.extend(reports)
../modules/loss.py:19:def compute_loss(output, reports_ids, reports_masks):
../modules/loss.py:21:    loss = criterion(output, reports_ids[:, 1:], reports_masks[:, 1:]).mean()
grep: ../modules/__pycache__/att_model.cpython-312.pyc: binary file matches
grep: ../modules/__pycache__/loss.cpython-312.pyc: binary file matches
grep: ../modules/__pycache__/trainer.cpython-312.pyc: binary file matches
grep: ../modules/__pycache__/caption_model.cpython-312.pyc: binary file matches
grep: ../modules/__pycache__/datasets.cpython-312.pyc: binary file matches
grep: ../modules/__pycache__/encoder_decoder.cpython-312.pyc: binary file matches
grep: ../modules/__pycache__/dataloaders.cpython-312.pyc: binary file matches
grep: ../modules/__pycache__/tokenizers.cpython-312.pyc: binary file matches
grep: ../modules/__pycache__/utils.cpython-312.pyc: binary file matches
../data/indiana_reports.csv:1766:1823,Nodule/lung/lower lobe/right;Calcinosis/lung/hilum/lymph nodes/right;Granuloma/lung/lower lobe/right,Nodule;Calcinosis;Granuloma,Xray Chest PA and Lateral,",786.50 pt.states has a soreness lt.lower and lateral rib and upper lt.abd.since having a mammogram one month ago.no XXXX or lung complaints./pkd",None. INDICATION /,"Chest. Heart size is normal. Pulmonary vasculature is normal. There is a 13 mm nodule in the right lower lobe that is relatively dense, but not obviously calcified on the corresponding rib series. There are probably right hilar calcified lymph XXXX. Lungs otherwise are clear. There is no pleural effusion. Left ribs. No fracture or focal bony destruction.","1. Chest. Large nodule at the right lung base that probably represents a granuloma although not it is not densely calcified. A low KV P chest radiograph can be obtained for confirmation as a there are no comparison studies available in the XXXX. If the patient has an outside chest radiograph, comparison can be XXXX and the report addended. 2. Ribs. Normal. Critical result notification documented through Primordial. If there are questions regarding this interpretation, please XXXX XXXX."
../data/indiana_reports.csv:2623:2721,"Calcified Granuloma/scattered/multiple;Aorta/tortuous;Calcinosis/aorta;Scoliosis/thoracic vertebrae;Kyphosis/severe;Bone Diseases, Metabolic/diffuse;Thoracic Vertebrae/degenerative/multiple;Deformity/thoracic vertebrae/multiple/mild","Calcified Granuloma;Aorta;Calcinosis;Scoliosis;Kyphosis;Bone Diseases, Metabolic;Thoracic Vertebrae;Deformity",Two views of the chest XXXX/XXXX.,"XXXX-year-old, preop carotid endarterectomy.","AP chest XXXX/XXXX, report only. Image not currently available.","Heart size at the upper limits of normal. There are scattered calcified granulomas. No focal airspace consolidation, large effusion, or appreciable pneumothorax. Tortuous, unfolded to descending aorta. Calcified aortic XXXX. XXXX curvature of the thoracic spine. Exaggerated kyphosis. XXXX are diffusely osteopenic. Multilevel degenerative changes of the thoracic spine with minimal anterior XXXX loss of several vertebral bodies.",Chronic changes without acute cardiopulmonary findings.
../data/indiana_reports.csv:2825:2942,normal,normal,"PA and Lateral Chest. XXXX, XXXX ",Followup on reported pneumonia,"XXXX, XXXX","Postsurgical changes of XXXX sternotomy with screw fixation of anterior XXXX plates. Heart size and cardiomediastinal silhouette are normal. No focal consolidation, suspicious bony opacity, pneumothorax, or pleural effusion. No acute osseous abnormality.",Interval postsurgical changes of XXXX sternotomy without acute cardiopulmonary abnormality.

In [23]:
for file in [
    "../modules/dataloaders.py",
    "../modules/datasets.py",
    "../modules/tokenizers.py",
]:
    print(f"\n===== {file} =====")
    try:
        with open(file, "r", encoding="utf-8") as f:
            lines = f.readlines()
        for i, line in enumerate(lines[:220], start=1):
            print(f"{i:4d}: {line.rstrip()}")
    except Exception as e:
        print("Could not read:", e)

===== ../modules/dataloaders.py =====
   1: import torch
   2: import numpy as np
   3: from torchvision import transforms
   4: from torch.utils.data import DataLoader
   5: from .datasets import IuxrayMultiImageDataset, MimiccxrSingleImageDataset
   6:
   7:
   8: class R2DataLoader(DataLoader):
   9:     def __init__(self, args, tokenizer, split, shuffle):
  10:         self.args = args
  11:         self.dataset_name = args.dataset_name
  12:         self.batch_size = args.batch_size
  13:         self.shuffle = shuffle
  14:         self.num_workers = args.num_workers
  15:         self.tokenizer = tokenizer
  16:         self.split = split
  17:
  18:         if split == 'train':
  19:             self.transform = transforms.Compose([
  20:                 transforms.Resize(256),
  21:                 transforms.RandomCrop(224),
  22:                 transforms.RandomHorizontalFlip(),
  23:                 transforms.ToTensor(),
  24:                 transforms.Normalize((0.485, 0.456, 0.406),
  25:                                      (0.229, 0.224, 0.225))])
  26:         else:
  27:             self.transform = transforms.Compose([
  28:                 transforms.Resize((224, 224)),
  29:                 transforms.ToTensor(),
  30:                 transforms.Normalize((0.485, 0.456, 0.406),
  31:                                      (0.229, 0.224, 0.225))])
  32:
  33:         if self.dataset_name == 'iu_xray':
  34:             self.dataset = IuxrayMultiImageDataset(self.args, self.tokenizer, self.split, transform=self.transform)
  35:         else:
  36:             self.dataset = MimiccxrSingleImageDataset(self.args, self.tokenizer, self.split, transform=self.transform)
  37:
  38:         self.init_kwargs = {
  39:             'dataset': self.dataset,
  40:             'batch_size': self.batch_size,
  41:             'shuffle': self.shuffle,
  42:             'collate_fn': self.collate_fn,
  43:             'num_workers': self.num_workers
  44:         }
  45:         super().__init__(**self.init_kwargs)
  46:
  47:     @staticmethod
  48:     def collate_fn(data):
  49:         images_id, images, reports_ids, reports_masks, seq_lengths = zip(*data)
  50:         images = torch.stack(images, 0)
  51:         max_seq_length = max(seq_lengths)
  52:
  53:         targets = np.zeros((len(reports_ids), max_seq_length), dtype=int)
  54:         targets_masks = np.zeros((len(reports_ids), max_seq_length), dtype=int)
  55:
  56:         for i, report_ids in enumerate(reports_ids):
  57:             targets[i, :len(report_ids)] = report_ids
  58:
  59:         for i, report_masks in enumerate(reports_masks):
  60:             targets_masks[i, :len(report_masks)] = report_masks
  61:
  62:         return images_id, images, torch.LongTensor(targets), torch.FloatTensor(targets_masks)
  63:

===== ../modules/datasets.py =====
   1: import os
   2: import json
   3: import torch
   4: import numpy as np
   5: from PIL import Image, ImageFile
   6: from torch.utils.data import Dataset
   7:
   8: ImageFile.LOAD_TRUNCATED_IMAGES = True
   9:
  10:
  11: class BaseDataset(Dataset):
  12:     def __init__(self, args, tokenizer, split, transform=None):
  13:
  14:         self.image_dir = args.image_dir
  15:         self.ann_path = args.ann_path
  16:         self.max_seq_length = args.max_seq_length
  17:         self.split = split
  18:         self.tokenizer = tokenizer
  19:         self.transform = transform
  20:
  21:         # Load annotations
  22:         with open(self.ann_path, 'r') as f:
  23:             self.ann = json.load(f)
  24:
  25:         # 🔥 Build label vocabulary from ALL splits
  26:         self.label2idx = self.build_label_vocab(self.ann)
  27:
  28:         # Current split data
  29:         self.examples = self.ann[self.split]
  30:
  31:         # Tokenize reports
  32:         for i in range(len(self.examples)):
  33:             tokens = tokenizer(self.examples[i]['report'])
  34:             tokens = tokens[:self.max_seq_length]
  35:
  36:             self.examples[i]['ids'] = tokens
  37:             self.examples[i]['mask'] = [1] * len(tokens)
  38:
  39:     def __len__(self):
  40:         return len(self.examples)
  41:
  42:     # ✅ Build vocabulary of Problems
  43:     def build_label_vocab(self, ann):
  44:         labels = set()
  45:
  46:         for split in ann:  # train / val / test
  47:             for sample in ann[split]:
  48:                 probs = sample.get('Problems', '')
  49:                 if probs:
  50:                     items = [p.strip() for p in probs.split(',')]
  51:                     labels.update(items)
  52:
  53:         label2idx = {l: i for i, l in enumerate(sorted(labels))}
  54:         print(f"[INFO] Total unique problem labels: {len(label2idx)}")
  55:
  56:         return label2idx
  57:
  58:     # ✅ Convert Problems → multi-hot vector
  59:     def encode_problems(self, probs):
  60:         vec = np.zeros(len(self.label2idx), dtype=np.float32)
  61:
  62:         if probs:
  63:             items = [p.strip() for p in probs.split(',')]
  64:             for item in items:
  65:                 if item in self.label2idx:
  66:                     vec[self.label2idx[item]] = 1.0
  67:
  68:         return vec
  69:
  70:
  71: # ======================================================
  72: # IU X-RAY (2 images)
  73: # ======================================================
  74: class IuxrayMultiImageDataset(BaseDataset):
  75:     def __getitem__(self, idx):
  76:         example = self.examples[idx]
  77:
  78:         image_id = example['id']
  79:         image_path = example['image_path']
  80:
  81:         # --- Load images safely ---
  82:         try:
  83:             image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  84:         except:
  85:             image_1 = Image.new('RGB', (224, 224))
  86:
  87:         if len(image_path) > 1:
  88:             try:
  89:                 image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  90:             except:
  91:                 image_2 = image_1
  92:         else:
  93:             image_2 = image_1
  94:
  95:         # --- Apply transforms ---
  96:         if self.transform is not None:
  97:             image_1 = self.transform(image_1)
  98:             image_2 = self.transform(image_2)
  99:
 100:         # Stack → (2, C, H, W)
 101:         image = torch.stack((image_1, image_2), 0)
 102:
 103:         # --- Report ---
 104:         report_ids = example['ids']
 105:         report_masks = example['mask']
 106:         seq_length = len(report_ids)
 107:
 108:         # --- Problems (NEW FEATURE) ---
 109:         problem_vec = self.encode_problems(example.get('Problems', ''))
 110:         problem_vec = torch.FloatTensor(problem_vec)
 111:
 112:         return image_id, image, problem_vec, report_ids, report_masks, seq_length
 113:
 114:
 115: # ======================================================
 116: # MIMIC-CXR (single image)
 117: # ======================================================
 118: class MimiccxrSingleImageDataset(BaseDataset):
 119:     def __getitem__(self, idx):
 120:         example = self.examples[idx]
 121:
 122:         image_id = example['id']
 123:         image_path = example['image_path']
 124:
 125:         image = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
 126:
 127:         if self.transform is not None:
 128:             image = self.transform(image)
 129:
 130:         report_ids = example['ids']
 131:         report_masks = example['mask']
 132:         seq_length = len(report_ids)
 133:
 134:         # Optional: include Problems here too if dataset supports it
 135:         problem_vec = self.encode_problems(example.get('Problems', ''))
 136:         problem_vec = torch.FloatTensor(problem_vec)
 137:
 138:         return image_id, image, problem_vec, report_ids, report_masks, seq_length

===== ../modules/tokenizers.py =====
   1: import json
   2: import re
   3: from collections import Counter
   4:
   5:
   6: class Tokenizer(object):
   7:     def __init__(self, args):
   8:         self.ann_path = args.ann_path
   9:         self.threshold = args.threshold
  10:         self.dataset_name = args.dataset_name
  11:         if self.dataset_name == 'iu_xray':
  12:             self.clean_report = self.clean_report_iu_xray
  13:         else:
  14:             self.clean_report = self.clean_report_mimic_cxr
  15:         self.ann = json.loads(open(self.ann_path, 'r').read())
  16:         self.token2idx, self.idx2token = self.create_vocabulary()
  17:
  18:     def create_vocabulary(self):
  19:         total_tokens = []
  20:
  21:         for example in self.ann['train']:
  22:             tokens = self.clean_report(example['report']).split()
  23:             for token in tokens:
  24:                 total_tokens.append(token)
  25:
  26:         counter = Counter(total_tokens)
  27:         vocab = [k for k, v in counter.items() if v >= self.threshold] + ['<unk>']
  28:         vocab.sort()
  29:         token2idx, idx2token = {}, {}
  30:         for idx, token in enumerate(vocab):
  31:             token2idx[token] = idx + 1
  32:             idx2token[idx + 1] = token
  33:         return token2idx, idx2token
  34:
  35:     def clean_report_iu_xray(self, report):
  36:         report_cleaner = lambda t: t.replace('..', '.').replace('..', '.').replace('..', '.').replace('1. ', '') \
  37:             .replace('. 2. ', '. ').replace('. 3. ', '. ').replace('. 4. ', '. ').replace('. 5. ', '. ') \
  38:             .replace(' 2. ', '. ').replace(' 3. ', '. ').replace(' 4. ', '. ').replace(' 5. ', '. ') \
  39:             .strip().lower().split('. ')
  40:         sent_cleaner = lambda t: re.sub('[.,?;*!%^&_+():-\[\]{}]', '', t.replace('"', '').replace('/', '').
  41:                                         replace('\\', '').replace("'", '').strip().lower())
  42:         tokens = [sent_cleaner(sent) for sent in report_cleaner(report) if sent_cleaner(sent) != []]
  43:         report = ' . '.join(tokens) + ' .'
  44:         return report
  45:
  46:     def clean_report_mimic_cxr(self, report):
  47:         report_cleaner = lambda t: t.replace('\n', ' ').replace('__', '_').replace('__', '_').replace('__', '_') \
  48:             .replace('__', '_').replace('__', '_').replace('__', '_').replace('__', '_').replace('  ', ' ') \
  49:             .replace('  ', ' ').replace('  ', ' ').replace('  ', ' ').replace('  ', ' ').replace('  ', ' ') \
  50:             .replace('..', '.').replace('..', '.').replace('..', '.').replace('..', '.').replace('..', '.') \
  51:             .replace('..', '.').replace('..', '.').replace('..', '.').replace('1. ', '').replace('. 2. ', '. ') \
  52:             .replace('. 3. ', '. ').replace('. 4. ', '. ').replace('. 5. ', '. ').replace(' 2. ', '. ') \
  53:             .replace(' 3. ', '. ').replace(' 4. ', '. ').replace(' 5. ', '. ') \
  54:             .strip().lower().split('. ')
  55:         sent_cleaner = lambda t: re.sub('[.,?;*!%^&_+():-\[\]{}]', '', t.replace('"', '').replace('/', '')
  56:                                         .replace('\\', '').replace("'", '').strip().lower())
  57:         tokens = [sent_cleaner(sent) for sent in report_cleaner(report) if sent_cleaner(sent) != []]
  58:         report = ' . '.join(tokens) + ' .'
  59:         return report
  60:
  61:     def get_token_by_id(self, id):
  62:         return self.idx2token[id]
  63:
  64:     def get_id_by_token(self, token):
  65:         if token not in self.token2idx:
  66:             return self.token2idx['<unk>']
  67:         return self.token2idx[token]
  68:
  69:     def get_vocab_size(self):
  70:         return len(self.token2idx)
  71:
  72:     def __call__(self, report):
  73:         tokens = self.clean_report(report).split()
  74:         ids = []
  75:         for token in tokens:
  76:             ids.append(self.get_id_by_token(token))
  77:         ids = [0] + ids + [0]
  78:         return ids
  79:
  80:     def decode(self, ids):
  81:         txt = ''
  82:         for i, idx in enumerate(ids):
  83:             if idx > 0:
  84:                 if i >= 1:
  85:                     txt += ' '
  86:                 txt += self.idx2token[idx]
  87:             else:
  88:                 break
  89:         return txt
  90:
  91:     def decode_batch(self, ids_batch):
  92:         out = []
  93:         for ids in ids_batch:
  94:             out.append(self.decode(ids))
  95:         return out

In [25]:
import sys
#sys.path.append("../R2Gen")

from argparse import Namespace
from modules.tokenizers import Tokenizer
from modules.dataloaders import R2DataLoader

args = Namespace(
    image_dir="R2GenCMN/data/iu_xray/images",
    ann_path="../data/iu_xray/annotation.json",
    dataset_name="iu_xray",
    max_seq_length=60,
    threshold=3,
    num_workers=2,
    batch_size=2,
)

print("Building tokenizer...")
tokenizer = Tokenizer(args)
print("Tokenizer vocab size:", len(tokenizer.token2idx))

print("Building train loader...")
train_loader = R2DataLoader(args, tokenizer, split="train", shuffle=True)

batch = next(iter(train_loader))
print("Loaded one batch successfully.")
print(type(batch))
print(batch)

Building tokenizer...
Tokenizer vocab size: 669
Building train loader...
Loaded one batch successfully.
<class 'tuple'>
(('682', '1584'), tensor([[[[[-1.1418, -1.0904, -1.0562,  ..., -1.8439, -2.0323, -2.0665],
           [-0.8849, -0.8507, -0.8335,  ..., -1.5185, -1.7412, -1.9980],
           [-0.7137, -0.7137, -0.7137,  ..., -1.3644, -1.4843, -1.6898],
           ...,
           [-2.0665, -2.0665, -2.0665,  ..., -0.7479, -0.7137, -0.6623],
           [-2.0665, -2.0665, -2.0665,  ..., -0.7308, -0.7137, -0.6623],
           [-2.0665, -2.0665, -2.0665,  ..., -0.7308, -0.7137, -0.6623]],

          [[-1.0378, -0.9853, -0.9503,  ..., -1.7556, -1.9482, -1.9832],
           [-0.7752, -0.7402, -0.7227,  ..., -1.4230, -1.6506, -1.9132],
           [-0.6001, -0.6001, -0.6001,  ..., -1.2654, -1.3880, -1.5980],
           ...,
           [-1.9832, -1.9832, -1.9832,  ..., -0.6352, -0.6001, -0.5476],
           [-1.9832, -1.9832, -1.9832,  ..., -0.6176, -0.6001, -0.5476],
           [-1.9832, -1.9832, -1.9832,  ..., -0.6176, -0.6001, -0.5476]],

          [[-0.8110, -0.7587, -0.7238,  ..., -1.5256, -1.7173, -1.7522],
           [-0.5495, -0.5147, -0.4973,  ..., -1.1944, -1.4210, -1.6824],
           [-0.3753, -0.3753, -0.3753,  ..., -1.0376, -1.1596, -1.3687],
           ...,
           [-1.7522, -1.7522, -1.7522,  ..., -0.4101, -0.3753, -0.3230],
           [-1.7522, -1.7522, -1.7522,  ..., -0.3927, -0.3753, -0.3230],
           [-1.7522, -1.7522, -1.7522,  ..., -0.3927, -0.3753, -0.3230]]],


         [[[-0.4226, -0.5253, -0.8678,  ..., -2.1008, -2.1008, -2.1008],
           [-0.4397, -0.5424, -0.5767,  ..., -2.1008, -2.1008, -2.1008],
           [-0.4397, -0.5596, -1.0219,  ..., -2.1008, -2.1008, -2.1008],
           ...,
           [-0.9192, -1.6213, -2.0665,  ..., -2.1179, -2.1179, -2.1179],
           [-0.9020, -1.6042, -2.0665,  ..., -2.1179, -2.1179, -2.1179],
           [-0.8678, -1.5870, -2.0665,  ..., -2.1179, -2.1179, -2.1179]],

          [[-0.3025, -0.4076, -0.7577,  ..., -2.0182, -2.0182, -2.0182],
           [-0.3200, -0.4251, -0.4601,  ..., -2.0182, -2.0182, -2.0182],
           [-0.3200, -0.4426, -0.9153,  ..., -2.0182, -2.0182, -2.0182],
           ...,
           [-0.8102, -1.5280, -1.9832,  ..., -2.0357, -2.0357, -2.0357],
           [-0.7927, -1.5105, -1.9832,  ..., -2.0357, -2.0357, -2.0357],
           [-0.7577, -1.4930, -1.9832,  ..., -2.0357, -2.0357, -2.0357]],

          [[-0.0790, -0.1835, -0.5321,  ..., -1.7870, -1.7870, -1.7870],
           [-0.0964, -0.2010, -0.2358,  ..., -1.7870, -1.7870, -1.7870],
           [-0.0964, -0.2184, -0.6890,  ..., -1.7870, -1.7870, -1.7870],
           ...,
           [-0.5844, -1.2990, -1.7522,  ..., -1.8044, -1.8044, -1.8044],
           [-0.5670, -1.2816, -1.7522,  ..., -1.8044, -1.8044, -1.8044],
           [-0.5321, -1.2641, -1.7522,  ..., -1.8044, -1.8044, -1.8044]]]],



        [[[[-0.1828,  0.7419,  1.0159,  ...,  0.9132,  0.8789,  0.8276],
           [-0.1657,  0.8447,  1.0159,  ...,  0.8789,  0.9132,  0.8961],
           [-0.1143,  0.8961,  0.9646,  ...,  0.8618,  0.9303,  0.9303],
           ...,
           [-0.6623, -0.6623, -0.6623,  ..., -0.6281, -0.6281, -0.6281],
           [-0.6794, -0.6623, -0.6623,  ..., -0.6452, -0.6281, -0.6281],
           [-0.6794, -0.6794, -0.6794,  ..., -0.6452, -0.6281, -0.6281]],

          [[-0.0574,  0.8880,  1.1681,  ...,  1.0630,  1.0280,  0.9755],
           [-0.0399,  0.9930,  1.1681,  ...,  1.0280,  1.0630,  1.0455],
           [ 0.0126,  1.0455,  1.1155,  ...,  1.0105,  1.0805,  1.0805],
           ...,
           [-0.5476, -0.5476, -0.5476,  ..., -0.5126, -0.5126, -0.5126],
           [-0.5651, -0.5476, -0.5476,  ..., -0.5301, -0.5126, -0.5126],
           [-0.5651, -0.5651, -0.5651,  ..., -0.5301, -0.5126, -0.5126]],

          [[ 0.1651,  1.1062,  1.3851,  ...,  1.2805,  1.2457,  1.1934],
           [ 0.1825,  1.2108,  1.3851,  ...,  1.2457,  1.2805,  1.2631],
           [ 0.2348,  1.2631,  1.3328,  ...,  1.2282,  1.2980,  1.2980],
           ...,
           [-0.3230, -0.3230, -0.3230,  ..., -0.2881, -0.2881, -0.2881],
           [-0.3404, -0.3230, -0.3230,  ..., -0.3055, -0.2881, -0.2881],
           [-0.3404, -0.3404, -0.3404,  ..., -0.3055, -0.2881, -0.2881]]],


         [[[-1.8782, -1.8782, -1.8953,  ...,  1.0331,  0.9474,  0.8447],
           [-1.8782, -1.8782, -1.8953,  ...,  1.0331,  0.9474,  0.8276],
           [-1.8782, -1.8953, -1.8953,  ...,  1.0502,  0.9474,  0.8447],
           ...,
           [ 0.4508,  0.4508,  0.3994,  ..., -0.1314, -0.1486, -0.1828],
           [ 0.1426,  0.1254,  0.1083,  ..., -0.2684, -0.2856, -0.2856],
           [-0.1143, -0.1486, -0.1486,  ..., -0.3883, -0.4054, -0.4054]],

          [[-1.7906, -1.7906, -1.8081,  ...,  1.1856,  1.0980,  0.9930],
           [-1.7906, -1.7906, -1.8081,  ...,  1.1856,  1.0980,  0.9755],
           [-1.7906, -1.8081, -1.8081,  ...,  1.2031,  1.0980,  0.9930],
           ...,
           [ 0.5903,  0.5903,  0.5378,  ..., -0.0049, -0.0224, -0.0574],
           [ 0.2752,  0.2577,  0.2402,  ..., -0.1450, -0.1625, -0.1625],
           [ 0.0126, -0.0224, -0.0224,  ..., -0.2675, -0.2850, -0.2850]],

          [[-1.5604, -1.5604, -1.5779,  ...,  1.4025,  1.3154,  1.2108],
           [-1.5604, -1.5604, -1.5779,  ...,  1.4025,  1.3154,  1.1934],
           [-1.5604, -1.5779, -1.5779,  ...,  1.4200,  1.3154,  1.2108],
           ...,
           [ 0.8099,  0.8099,  0.7576,  ...,  0.2173,  0.1999,  0.1651],
           [ 0.4962,  0.4788,  0.4614,  ...,  0.0779,  0.0605,  0.0605],
           [ 0.2348,  0.1999,  0.1999,  ..., -0.0441, -0.0615, -0.0615]]]]]), tensor([[  0, 396,  23, 116, 193,   1, 396, 593, 486, 400, 422, 369,   1, 396,
         224, 415, 193, 501,   1,   0],
        [  0, 394, 252,  23, 116,  19,   1,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0]]), tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]]))

In [26]:
file_path = "../modules/datasets.py"

with open(file_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

for i, line in enumerate(lines, start=1):
    if "class " in line or "__init__" in line or "__getitem__" in line or "image_path" in line or "report" in line or "ann_path" in line:
        start = max(1, i - 8)
        end = min(len(lines), i + 25)
        print(f"\n--- lines {start} to {end} ---")
        for j in range(start, end + 1):
            print(f"{j:4d}: {lines[j-1].rstrip()}")

--- lines 3 to 36 ---
   3: import torch
   4: import numpy as np
   5: from PIL import Image, ImageFile
   6: from torch.utils.data import Dataset
   7:
   8: ImageFile.LOAD_TRUNCATED_IMAGES = True
   9:
  10:
  11: class BaseDataset(Dataset):
  12:     def __init__(self, args, tokenizer, split, transform=None):
  13:
  14:         self.image_dir = args.image_dir
  15:         self.ann_path = args.ann_path
  16:         self.max_seq_length = args.max_seq_length
  17:         self.split = split
  18:         self.tokenizer = tokenizer
  19:         self.transform = transform
  20:
  21:         # Load annotations
  22:         with open(self.ann_path, 'r') as f:
  23:             self.ann = json.load(f)
  24:
  25:         # 🔥 Build label vocabulary from ALL splits
  26:         self.label2idx = self.build_label_vocab(self.ann)
  27:
  28:         # Current split data
  29:         self.examples = self.ann[self.split]
  30:
  31:         # Tokenize reports
  32:         for i in range(len(self.examples)):
  33:             tokens = tokenizer(self.examples[i]['report'])
  34:             tokens = tokens[:self.max_seq_length]
  35:
  36:             self.examples[i]['ids'] = tokens

--- lines 4 to 37 ---
   4: import numpy as np
   5: from PIL import Image, ImageFile
   6: from torch.utils.data import Dataset
   7:
   8: ImageFile.LOAD_TRUNCATED_IMAGES = True
   9:
  10:
  11: class BaseDataset(Dataset):
  12:     def __init__(self, args, tokenizer, split, transform=None):
  13:
  14:         self.image_dir = args.image_dir
  15:         self.ann_path = args.ann_path
  16:         self.max_seq_length = args.max_seq_length
  17:         self.split = split
  18:         self.tokenizer = tokenizer
  19:         self.transform = transform
  20:
  21:         # Load annotations
  22:         with open(self.ann_path, 'r') as f:
  23:             self.ann = json.load(f)
  24:
  25:         # 🔥 Build label vocabulary from ALL splits
  26:         self.label2idx = self.build_label_vocab(self.ann)
  27:
  28:         # Current split data
  29:         self.examples = self.ann[self.split]
  30:
  31:         # Tokenize reports
  32:         for i in range(len(self.examples)):
  33:             tokens = tokenizer(self.examples[i]['report'])
  34:             tokens = tokens[:self.max_seq_length]
  35:
  36:             self.examples[i]['ids'] = tokens
  37:             self.examples[i]['mask'] = [1] * len(tokens)

--- lines 7 to 40 ---
   7:
   8: ImageFile.LOAD_TRUNCATED_IMAGES = True
   9:
  10:
  11: class BaseDataset(Dataset):
  12:     def __init__(self, args, tokenizer, split, transform=None):
  13:
  14:         self.image_dir = args.image_dir
  15:         self.ann_path = args.ann_path
  16:         self.max_seq_length = args.max_seq_length
  17:         self.split = split
  18:         self.tokenizer = tokenizer
  19:         self.transform = transform
  20:
  21:         # Load annotations
  22:         with open(self.ann_path, 'r') as f:
  23:             self.ann = json.load(f)
  24:
  25:         # 🔥 Build label vocabulary from ALL splits
  26:         self.label2idx = self.build_label_vocab(self.ann)
  27:
  28:         # Current split data
  29:         self.examples = self.ann[self.split]
  30:
  31:         # Tokenize reports
  32:         for i in range(len(self.examples)):
  33:             tokens = tokenizer(self.examples[i]['report'])
  34:             tokens = tokens[:self.max_seq_length]
  35:
  36:             self.examples[i]['ids'] = tokens
  37:             self.examples[i]['mask'] = [1] * len(tokens)
  38:
  39:     def __len__(self):
  40:         return len(self.examples)

--- lines 14 to 47 ---
  14:         self.image_dir = args.image_dir
  15:         self.ann_path = args.ann_path
  16:         self.max_seq_length = args.max_seq_length
  17:         self.split = split
  18:         self.tokenizer = tokenizer
  19:         self.transform = transform
  20:
  21:         # Load annotations
  22:         with open(self.ann_path, 'r') as f:
  23:             self.ann = json.load(f)
  24:
  25:         # 🔥 Build label vocabulary from ALL splits
  26:         self.label2idx = self.build_label_vocab(self.ann)
  27:
  28:         # Current split data
  29:         self.examples = self.ann[self.split]
  30:
  31:         # Tokenize reports
  32:         for i in range(len(self.examples)):
  33:             tokens = tokenizer(self.examples[i]['report'])
  34:             tokens = tokens[:self.max_seq_length]
  35:
  36:             self.examples[i]['ids'] = tokens
  37:             self.examples[i]['mask'] = [1] * len(tokens)
  38:
  39:     def __len__(self):
  40:         return len(self.examples)
  41:
  42:     # ✅ Build vocabulary of Problems
  43:     def build_label_vocab(self, ann):
  44:         labels = set()
  45:
  46:         for split in ann:  # train / val / test
  47:             for sample in ann[split]:

--- lines 23 to 56 ---
  23:             self.ann = json.load(f)
  24:
  25:         # 🔥 Build label vocabulary from ALL splits
  26:         self.label2idx = self.build_label_vocab(self.ann)
  27:
  28:         # Current split data
  29:         self.examples = self.ann[self.split]
  30:
  31:         # Tokenize reports
  32:         for i in range(len(self.examples)):
  33:             tokens = tokenizer(self.examples[i]['report'])
  34:             tokens = tokens[:self.max_seq_length]
  35:
  36:             self.examples[i]['ids'] = tokens
  37:             self.examples[i]['mask'] = [1] * len(tokens)
  38:
  39:     def __len__(self):
  40:         return len(self.examples)
  41:
  42:     # ✅ Build vocabulary of Problems
  43:     def build_label_vocab(self, ann):
  44:         labels = set()
  45:
  46:         for split in ann:  # train / val / test
  47:             for sample in ann[split]:
  48:                 probs = sample.get('Problems', '')
  49:                 if probs:
  50:                     items = [p.strip() for p in probs.split(',')]
  51:                     labels.update(items)
  52:
  53:         label2idx = {l: i for i, l in enumerate(sorted(labels))}
  54:         print(f"[INFO] Total unique problem labels: {len(label2idx)}")
  55:
  56:         return label2idx

--- lines 25 to 58 ---
  25:         # 🔥 Build label vocabulary from ALL splits
  26:         self.label2idx = self.build_label_vocab(self.ann)
  27:
  28:         # Current split data
  29:         self.examples = self.ann[self.split]
  30:
  31:         # Tokenize reports
  32:         for i in range(len(self.examples)):
  33:             tokens = tokenizer(self.examples[i]['report'])
  34:             tokens = tokens[:self.max_seq_length]
  35:
  36:             self.examples[i]['ids'] = tokens
  37:             self.examples[i]['mask'] = [1] * len(tokens)
  38:
  39:     def __len__(self):
  40:         return len(self.examples)
  41:
  42:     # ✅ Build vocabulary of Problems
  43:     def build_label_vocab(self, ann):
  44:         labels = set()
  45:
  46:         for split in ann:  # train / val / test
  47:             for sample in ann[split]:
  48:                 probs = sample.get('Problems', '')
  49:                 if probs:
  50:                     items = [p.strip() for p in probs.split(',')]
  51:                     labels.update(items)
  52:
  53:         label2idx = {l: i for i, l in enumerate(sorted(labels))}
  54:         print(f"[INFO] Total unique problem labels: {len(label2idx)}")
  55:
  56:         return label2idx
  57:
  58:     # ✅ Convert Problems → multi-hot vector

--- lines 66 to 99 ---
  66:                     vec[self.label2idx[item]] = 1.0
  67:
  68:         return vec
  69:
  70:
  71: # ======================================================
  72: # IU X-RAY (2 images)
  73: # ======================================================
  74: class IuxrayMultiImageDataset(BaseDataset):
  75:     def __getitem__(self, idx):
  76:         example = self.examples[idx]
  77:
  78:         image_id = example['id']
  79:         image_path = example['image_path']
  80:
  81:         # --- Load images safely ---
  82:         try:
  83:             image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  84:         except:
  85:             image_1 = Image.new('RGB', (224, 224))
  86:
  87:         if len(image_path) > 1:
  88:             try:
  89:                 image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  90:             except:
  91:                 image_2 = image_1
  92:         else:
  93:             image_2 = image_1
  94:
  95:         # --- Apply transforms ---
  96:         if self.transform is not None:
  97:             image_1 = self.transform(image_1)
  98:             image_2 = self.transform(image_2)
  99:

--- lines 67 to 100 ---
  67:
  68:         return vec
  69:
  70:
  71: # ======================================================
  72: # IU X-RAY (2 images)
  73: # ======================================================
  74: class IuxrayMultiImageDataset(BaseDataset):
  75:     def __getitem__(self, idx):
  76:         example = self.examples[idx]
  77:
  78:         image_id = example['id']
  79:         image_path = example['image_path']
  80:
  81:         # --- Load images safely ---
  82:         try:
  83:             image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  84:         except:
  85:             image_1 = Image.new('RGB', (224, 224))
  86:
  87:         if len(image_path) > 1:
  88:             try:
  89:                 image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  90:             except:
  91:                 image_2 = image_1
  92:         else:
  93:             image_2 = image_1
  94:
  95:         # --- Apply transforms ---
  96:         if self.transform is not None:
  97:             image_1 = self.transform(image_1)
  98:             image_2 = self.transform(image_2)
  99:
 100:         # Stack → (2, C, H, W)

--- lines 71 to 104 ---
  71: # ======================================================
  72: # IU X-RAY (2 images)
  73: # ======================================================
  74: class IuxrayMultiImageDataset(BaseDataset):
  75:     def __getitem__(self, idx):
  76:         example = self.examples[idx]
  77:
  78:         image_id = example['id']
  79:         image_path = example['image_path']
  80:
  81:         # --- Load images safely ---
  82:         try:
  83:             image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  84:         except:
  85:             image_1 = Image.new('RGB', (224, 224))
  86:
  87:         if len(image_path) > 1:
  88:             try:
  89:                 image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  90:             except:
  91:                 image_2 = image_1
  92:         else:
  93:             image_2 = image_1
  94:
  95:         # --- Apply transforms ---
  96:         if self.transform is not None:
  97:             image_1 = self.transform(image_1)
  98:             image_2 = self.transform(image_2)
  99:
 100:         # Stack → (2, C, H, W)
 101:         image = torch.stack((image_1, image_2), 0)
 102:
 103:         # --- Report ---
 104:         report_ids = example['ids']

--- lines 75 to 108 ---
  75:     def __getitem__(self, idx):
  76:         example = self.examples[idx]
  77:
  78:         image_id = example['id']
  79:         image_path = example['image_path']
  80:
  81:         # --- Load images safely ---
  82:         try:
  83:             image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  84:         except:
  85:             image_1 = Image.new('RGB', (224, 224))
  86:
  87:         if len(image_path) > 1:
  88:             try:
  89:                 image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  90:             except:
  91:                 image_2 = image_1
  92:         else:
  93:             image_2 = image_1
  94:
  95:         # --- Apply transforms ---
  96:         if self.transform is not None:
  97:             image_1 = self.transform(image_1)
  98:             image_2 = self.transform(image_2)
  99:
 100:         # Stack → (2, C, H, W)
 101:         image = torch.stack((image_1, image_2), 0)
 102:
 103:         # --- Report ---
 104:         report_ids = example['ids']
 105:         report_masks = example['mask']
 106:         seq_length = len(report_ids)
 107:
 108:         # --- Problems (NEW FEATURE) ---

--- lines 79 to 112 ---
  79:         image_path = example['image_path']
  80:
  81:         # --- Load images safely ---
  82:         try:
  83:             image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  84:         except:
  85:             image_1 = Image.new('RGB', (224, 224))
  86:
  87:         if len(image_path) > 1:
  88:             try:
  89:                 image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  90:             except:
  91:                 image_2 = image_1
  92:         else:
  93:             image_2 = image_1
  94:
  95:         # --- Apply transforms ---
  96:         if self.transform is not None:
  97:             image_1 = self.transform(image_1)
  98:             image_2 = self.transform(image_2)
  99:
 100:         # Stack → (2, C, H, W)
 101:         image = torch.stack((image_1, image_2), 0)
 102:
 103:         # --- Report ---
 104:         report_ids = example['ids']
 105:         report_masks = example['mask']
 106:         seq_length = len(report_ids)
 107:
 108:         # --- Problems (NEW FEATURE) ---
 109:         problem_vec = self.encode_problems(example.get('Problems', ''))
 110:         problem_vec = torch.FloatTensor(problem_vec)
 111:
 112:         return image_id, image, problem_vec, report_ids, report_masks, seq_length

--- lines 81 to 114 ---
  81:         # --- Load images safely ---
  82:         try:
  83:             image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  84:         except:
  85:             image_1 = Image.new('RGB', (224, 224))
  86:
  87:         if len(image_path) > 1:
  88:             try:
  89:                 image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  90:             except:
  91:                 image_2 = image_1
  92:         else:
  93:             image_2 = image_1
  94:
  95:         # --- Apply transforms ---
  96:         if self.transform is not None:
  97:             image_1 = self.transform(image_1)
  98:             image_2 = self.transform(image_2)
  99:
 100:         # Stack → (2, C, H, W)
 101:         image = torch.stack((image_1, image_2), 0)
 102:
 103:         # --- Report ---
 104:         report_ids = example['ids']
 105:         report_masks = example['mask']
 106:         seq_length = len(report_ids)
 107:
 108:         # --- Problems (NEW FEATURE) ---
 109:         problem_vec = self.encode_problems(example.get('Problems', ''))
 110:         problem_vec = torch.FloatTensor(problem_vec)
 111:
 112:         return image_id, image, problem_vec, report_ids, report_masks, seq_length
 113:
 114:

--- lines 96 to 129 ---
  96:         if self.transform is not None:
  97:             image_1 = self.transform(image_1)
  98:             image_2 = self.transform(image_2)
  99:
 100:         # Stack → (2, C, H, W)
 101:         image = torch.stack((image_1, image_2), 0)
 102:
 103:         # --- Report ---
 104:         report_ids = example['ids']
 105:         report_masks = example['mask']
 106:         seq_length = len(report_ids)
 107:
 108:         # --- Problems (NEW FEATURE) ---
 109:         problem_vec = self.encode_problems(example.get('Problems', ''))
 110:         problem_vec = torch.FloatTensor(problem_vec)
 111:
 112:         return image_id, image, problem_vec, report_ids, report_masks, seq_length
 113:
 114:
 115: # ======================================================
 116: # MIMIC-CXR (single image)
 117: # ======================================================
 118: class MimiccxrSingleImageDataset(BaseDataset):
 119:     def __getitem__(self, idx):
 120:         example = self.examples[idx]
 121:
 122:         image_id = example['id']
 123:         image_path = example['image_path']
 124:
 125:         image = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
 126:
 127:         if self.transform is not None:
 128:             image = self.transform(image)
 129:

--- lines 97 to 130 ---
  97:             image_1 = self.transform(image_1)
  98:             image_2 = self.transform(image_2)
  99:
 100:         # Stack → (2, C, H, W)
 101:         image = torch.stack((image_1, image_2), 0)
 102:
 103:         # --- Report ---
 104:         report_ids = example['ids']
 105:         report_masks = example['mask']
 106:         seq_length = len(report_ids)
 107:
 108:         # --- Problems (NEW FEATURE) ---
 109:         problem_vec = self.encode_problems(example.get('Problems', ''))
 110:         problem_vec = torch.FloatTensor(problem_vec)
 111:
 112:         return image_id, image, problem_vec, report_ids, report_masks, seq_length
 113:
 114:
 115: # ======================================================
 116: # MIMIC-CXR (single image)
 117: # ======================================================
 118: class MimiccxrSingleImageDataset(BaseDataset):
 119:     def __getitem__(self, idx):
 120:         example = self.examples[idx]
 121:
 122:         image_id = example['id']
 123:         image_path = example['image_path']
 124:
 125:         image = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
 126:
 127:         if self.transform is not None:
 128:             image = self.transform(image)
 129:
 130:         report_ids = example['ids']

--- lines 98 to 131 ---
  98:             image_2 = self.transform(image_2)
  99:
 100:         # Stack → (2, C, H, W)
 101:         image = torch.stack((image_1, image_2), 0)
 102:
 103:         # --- Report ---
 104:         report_ids = example['ids']
 105:         report_masks = example['mask']
 106:         seq_length = len(report_ids)
 107:
 108:         # --- Problems (NEW FEATURE) ---
 109:         problem_vec = self.encode_problems(example.get('Problems', ''))
 110:         problem_vec = torch.FloatTensor(problem_vec)
 111:
 112:         return image_id, image, problem_vec, report_ids, report_masks, seq_length
 113:
 114:
 115: # ======================================================
 116: # MIMIC-CXR (single image)
 117: # ======================================================
 118: class MimiccxrSingleImageDataset(BaseDataset):
 119:     def __getitem__(self, idx):
 120:         example = self.examples[idx]
 121:
 122:         image_id = example['id']
 123:         image_path = example['image_path']
 124:
 125:         image = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
 126:
 127:         if self.transform is not None:
 128:             image = self.transform(image)
 129:
 130:         report_ids = example['ids']
 131:         report_masks = example['mask']

--- lines 104 to 137 ---
 104:         report_ids = example['ids']
 105:         report_masks = example['mask']
 106:         seq_length = len(report_ids)
 107:
 108:         # --- Problems (NEW FEATURE) ---
 109:         problem_vec = self.encode_problems(example.get('Problems', ''))
 110:         problem_vec = torch.FloatTensor(problem_vec)
 111:
 112:         return image_id, image, problem_vec, report_ids, report_masks, seq_length
 113:
 114:
 115: # ======================================================
 116: # MIMIC-CXR (single image)
 117: # ======================================================
 118: class MimiccxrSingleImageDataset(BaseDataset):
 119:     def __getitem__(self, idx):
 120:         example = self.examples[idx]
 121:

In [27]:
file_path = "../modules/datasets.py"

with open(file_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

keywords = ["class BaseDataset", "def __init__", "json.load", "self.examples", "tokenizer", "ids", "mask", "report"]

for i, line in enumerate(lines, start=1):
    if any(k in line for k in keywords):
        start = max(1, i - 10)
        end = min(len(lines), i + 35)
        print(f"\n--- lines {start} to {end} ---")
        for j in range(start, end + 1):
            print(f"{j:4d}: {lines[j-1].rstrip()}")

--- lines 1 to 46 ---
   1: import os
   2: import json
   3: import torch
   4: import numpy as np
   5: from PIL import Image, ImageFile
   6: from torch.utils.data import Dataset
   7:
   8: ImageFile.LOAD_TRUNCATED_IMAGES = True
   9:
  10:
  11: class BaseDataset(Dataset):
  12:     def __init__(self, args, tokenizer, split, transform=None):
  13:
  14:         self.image_dir = args.image_dir
  15:         self.ann_path = args.ann_path
  16:         self.max_seq_length = args.max_seq_length
  17:         self.split = split
  18:         self.tokenizer = tokenizer
  19:         self.transform = transform
  20:
  21:         # Load annotations
  22:         with open(self.ann_path, 'r') as f:
  23:             self.ann = json.load(f)
  24:
  25:         # 🔥 Build label vocabulary from ALL splits
  26:         self.label2idx = self.build_label_vocab(self.ann)
  27:
  28:         # Current split data
  29:         self.examples = self.ann[self.split]
  30:
  31:         # Tokenize reports
  32:         for i in range(len(self.examples)):
  33:             tokens = tokenizer(self.examples[i]['report'])
  34:             tokens = tokens[:self.max_seq_length]
  35:
  36:             self.examples[i]['ids'] = tokens
  37:             self.examples[i]['mask'] = [1] * len(tokens)
  38:
  39:     def __len__(self):
  40:         return len(self.examples)
  41:
  42:     # ✅ Build vocabulary of Problems
  43:     def build_label_vocab(self, ann):
  44:         labels = set()
  45:
  46:         for split in ann:  # train / val / test

--- lines 2 to 47 ---
   2: import json
   3: import torch
   4: import numpy as np
   5: from PIL import Image, ImageFile
   6: from torch.utils.data import Dataset
   7:
   8: ImageFile.LOAD_TRUNCATED_IMAGES = True
   9:
  10:
  11: class BaseDataset(Dataset):
  12:     def __init__(self, args, tokenizer, split, transform=None):
  13:
  14:         self.image_dir = args.image_dir
  15:         self.ann_path = args.ann_path
  16:         self.max_seq_length = args.max_seq_length
  17:         self.split = split
  18:         self.tokenizer = tokenizer
  19:         self.transform = transform
  20:
  21:         # Load annotations
  22:         with open(self.ann_path, 'r') as f:
  23:             self.ann = json.load(f)
  24:
  25:         # 🔥 Build label vocabulary from ALL splits
  26:         self.label2idx = self.build_label_vocab(self.ann)
  27:
  28:         # Current split data
  29:         self.examples = self.ann[self.split]
  30:
  31:         # Tokenize reports
  32:         for i in range(len(self.examples)):
  33:             tokens = tokenizer(self.examples[i]['report'])
  34:             tokens = tokens[:self.max_seq_length]
  35:
  36:             self.examples[i]['ids'] = tokens
  37:             self.examples[i]['mask'] = [1] * len(tokens)
  38:
  39:     def __len__(self):
  40:         return len(self.examples)
  41:
  42:     # ✅ Build vocabulary of Problems
  43:     def build_label_vocab(self, ann):
  44:         labels = set()
  45:
  46:         for split in ann:  # train / val / test
  47:             for sample in ann[split]:

--- lines 8 to 53 ---
   8: ImageFile.LOAD_TRUNCATED_IMAGES = True
   9:
  10:
  11: class BaseDataset(Dataset):
  12:     def __init__(self, args, tokenizer, split, transform=None):
  13:
  14:         self.image_dir = args.image_dir
  15:         self.ann_path = args.ann_path
  16:         self.max_seq_length = args.max_seq_length
  17:         self.split = split
  18:         self.tokenizer = tokenizer
  19:         self.transform = transform
  20:
  21:         # Load annotations
  22:         with open(self.ann_path, 'r') as f:
  23:             self.ann = json.load(f)
  24:
  25:         # 🔥 Build label vocabulary from ALL splits
  26:         self.label2idx = self.build_label_vocab(self.ann)
  27:
  28:         # Current split data
  29:         self.examples = self.ann[self.split]
  30:
  31:         # Tokenize reports
  32:         for i in range(len(self.examples)):
  33:             tokens = tokenizer(self.examples[i]['report'])
  34:             tokens = tokens[:self.max_seq_length]
  35:
  36:             self.examples[i]['ids'] = tokens
  37:             self.examples[i]['mask'] = [1] * len(tokens)
  38:
  39:     def __len__(self):
  40:         return len(self.examples)
  41:
  42:     # ✅ Build vocabulary of Problems
  43:     def build_label_vocab(self, ann):
  44:         labels = set()
  45:
  46:         for split in ann:  # train / val / test
  47:             for sample in ann[split]:
  48:                 probs = sample.get('Problems', '')
  49:                 if probs:
  50:                     items = [p.strip() for p in probs.split(',')]
  51:                     labels.update(items)
  52:
  53:         label2idx = {l: i for i, l in enumerate(sorted(labels))}

--- lines 13 to 58 ---
  13:
  14:         self.image_dir = args.image_dir
  15:         self.ann_path = args.ann_path
  16:         self.max_seq_length = args.max_seq_length
  17:         self.split = split
  18:         self.tokenizer = tokenizer
  19:         self.transform = transform
  20:
  21:         # Load annotations
  22:         with open(self.ann_path, 'r') as f:
  23:             self.ann = json.load(f)
  24:
  25:         # 🔥 Build label vocabulary from ALL splits
  26:         self.label2idx = self.build_label_vocab(self.ann)
  27:
  28:         # Current split data
  29:         self.examples = self.ann[self.split]
  30:
  31:         # Tokenize reports
  32:         for i in range(len(self.examples)):
  33:             tokens = tokenizer(self.examples[i]['report'])
  34:             tokens = tokens[:self.max_seq_length]
  35:
  36:             self.examples[i]['ids'] = tokens
  37:             self.examples[i]['mask'] = [1] * len(tokens)
  38:
  39:     def __len__(self):
  40:         return len(self.examples)
  41:
  42:     # ✅ Build vocabulary of Problems
  43:     def build_label_vocab(self, ann):
  44:         labels = set()
  45:
  46:         for split in ann:  # train / val / test
  47:             for sample in ann[split]:
  48:                 probs = sample.get('Problems', '')
  49:                 if probs:
  50:                     items = [p.strip() for p in probs.split(',')]
  51:                     labels.update(items)
  52:
  53:         label2idx = {l: i for i, l in enumerate(sorted(labels))}
  54:         print(f"[INFO] Total unique problem labels: {len(label2idx)}")
  55:
  56:         return label2idx
  57:
  58:     # ✅ Convert Problems → multi-hot vector

--- lines 19 to 64 ---
  19:         self.transform = transform
  20:
  21:         # Load annotations
  22:         with open(self.ann_path, 'r') as f:
  23:             self.ann = json.load(f)
  24:
  25:         # 🔥 Build label vocabulary from ALL splits
  26:         self.label2idx = self.build_label_vocab(self.ann)
  27:
  28:         # Current split data
  29:         self.examples = self.ann[self.split]
  30:
  31:         # Tokenize reports
  32:         for i in range(len(self.examples)):
  33:             tokens = tokenizer(self.examples[i]['report'])
  34:             tokens = tokens[:self.max_seq_length]
  35:
  36:             self.examples[i]['ids'] = tokens
  37:             self.examples[i]['mask'] = [1] * len(tokens)
  38:
  39:     def __len__(self):
  40:         return len(self.examples)
  41:
  42:     # ✅ Build vocabulary of Problems
  43:     def build_label_vocab(self, ann):
  44:         labels = set()
  45:
  46:         for split in ann:  # train / val / test
  47:             for sample in ann[split]:
  48:                 probs = sample.get('Problems', '')
  49:                 if probs:
  50:                     items = [p.strip() for p in probs.split(',')]
  51:                     labels.update(items)
  52:
  53:         label2idx = {l: i for i, l in enumerate(sorted(labels))}
  54:         print(f"[INFO] Total unique problem labels: {len(label2idx)}")
  55:
  56:         return label2idx
  57:
  58:     # ✅ Convert Problems → multi-hot vector
  59:     def encode_problems(self, probs):
  60:         vec = np.zeros(len(self.label2idx), dtype=np.float32)
  61:
  62:         if probs:
  63:             items = [p.strip() for p in probs.split(',')]
  64:             for item in items:

--- lines 21 to 66 ---
  21:         # Load annotations
  22:         with open(self.ann_path, 'r') as f:
  23:             self.ann = json.load(f)
  24:
  25:         # 🔥 Build label vocabulary from ALL splits
  26:         self.label2idx = self.build_label_vocab(self.ann)
  27:
  28:         # Current split data
  29:         self.examples = self.ann[self.split]
  30:
  31:         # Tokenize reports
  32:         for i in range(len(self.examples)):
  33:             tokens = tokenizer(self.examples[i]['report'])
  34:             tokens = tokens[:self.max_seq_length]
  35:
  36:             self.examples[i]['ids'] = tokens
  37:             self.examples[i]['mask'] = [1] * len(tokens)
  38:
  39:     def __len__(self):
  40:         return len(self.examples)
  41:
  42:     # ✅ Build vocabulary of Problems
  43:     def build_label_vocab(self, ann):
  44:         labels = set()
  45:
  46:         for split in ann:  # train / val / test
  47:             for sample in ann[split]:
  48:                 probs = sample.get('Problems', '')
  49:                 if probs:
  50:                     items = [p.strip() for p in probs.split(',')]
  51:                     labels.update(items)
  52:
  53:         label2idx = {l: i for i, l in enumerate(sorted(labels))}
  54:         print(f"[INFO] Total unique problem labels: {len(label2idx)}")
  55:
  56:         return label2idx
  57:
  58:     # ✅ Convert Problems → multi-hot vector
  59:     def encode_problems(self, probs):
  60:         vec = np.zeros(len(self.label2idx), dtype=np.float32)
  61:
  62:         if probs:
  63:             items = [p.strip() for p in probs.split(',')]
  64:             for item in items:
  65:                 if item in self.label2idx:
  66:                     vec[self.label2idx[item]] = 1.0

--- lines 22 to 67 ---
  22:         with open(self.ann_path, 'r') as f:
  23:             self.ann = json.load(f)
  24:
  25:         # 🔥 Build label vocabulary from ALL splits
  26:         self.label2idx = self.build_label_vocab(self.ann)
  27:
  28:         # Current split data
  29:         self.examples = self.ann[self.split]
  30:
  31:         # Tokenize reports
  32:         for i in range(len(self.examples)):
  33:             tokens = tokenizer(self.examples[i]['report'])
  34:             tokens = tokens[:self.max_seq_length]
  35:
  36:             self.examples[i]['ids'] = tokens
  37:             self.examples[i]['mask'] = [1] * len(tokens)
  38:
  39:     def __len__(self):
  40:         return len(self.examples)
  41:
  42:     # ✅ Build vocabulary of Problems
  43:     def build_label_vocab(self, ann):
  44:         labels = set()
  45:
  46:         for split in ann:  # train / val / test
  47:             for sample in ann[split]:
  48:                 probs = sample.get('Problems', '')
  49:                 if probs:
  50:                     items = [p.strip() for p in probs.split(',')]
  51:                     labels.update(items)
  52:
  53:         label2idx = {l: i for i, l in enumerate(sorted(labels))}
  54:         print(f"[INFO] Total unique problem labels: {len(label2idx)}")
  55:
  56:         return label2idx
  57:
  58:     # ✅ Convert Problems → multi-hot vector
  59:     def encode_problems(self, probs):
  60:         vec = np.zeros(len(self.label2idx), dtype=np.float32)
  61:
  62:         if probs:
  63:             items = [p.strip() for p in probs.split(',')]
  64:             for item in items:
  65:                 if item in self.label2idx:
  66:                     vec[self.label2idx[item]] = 1.0
  67:

--- lines 23 to 68 ---
  23:             self.ann = json.load(f)
  24:
  25:         # 🔥 Build label vocabulary from ALL splits
  26:         self.label2idx = self.build_label_vocab(self.ann)
  27:
  28:         # Current split data
  29:         self.examples = self.ann[self.split]
  30:
  31:         # Tokenize reports
  32:         for i in range(len(self.examples)):
  33:             tokens = tokenizer(self.examples[i]['report'])
  34:             tokens = tokens[:self.max_seq_length]
  35:
  36:             self.examples[i]['ids'] = tokens
  37:             self.examples[i]['mask'] = [1] * len(tokens)
  38:
  39:     def __len__(self):
  40:         return len(self.examples)
  41:
  42:     # ✅ Build vocabulary of Problems
  43:     def build_label_vocab(self, ann):
  44:         labels = set()
  45:
  46:         for split in ann:  # train / val / test
  47:             for sample in ann[split]:
  48:                 probs = sample.get('Problems', '')
  49:                 if probs:
  50:                     items = [p.strip() for p in probs.split(',')]
  51:                     labels.update(items)
  52:
  53:         label2idx = {l: i for i, l in enumerate(sorted(labels))}
  54:         print(f"[INFO] Total unique problem labels: {len(label2idx)}")
  55:
  56:         return label2idx
  57:
  58:     # ✅ Convert Problems → multi-hot vector
  59:     def encode_problems(self, probs):
  60:         vec = np.zeros(len(self.label2idx), dtype=np.float32)
  61:
  62:         if probs:
  63:             items = [p.strip() for p in probs.split(',')]
  64:             for item in items:
  65:                 if item in self.label2idx:
  66:                     vec[self.label2idx[item]] = 1.0
  67:
  68:         return vec

--- lines 26 to 71 ---
  26:         self.label2idx = self.build_label_vocab(self.ann)
  27:
  28:         # Current split data
  29:         self.examples = self.ann[self.split]
  30:
  31:         # Tokenize reports
  32:         for i in range(len(self.examples)):
  33:             tokens = tokenizer(self.examples[i]['report'])
  34:             tokens = tokens[:self.max_seq_length]
  35:
  36:             self.examples[i]['ids'] = tokens
  37:             self.examples[i]['mask'] = [1] * len(tokens)
  38:
  39:     def __len__(self):
  40:         return len(self.examples)
  41:
  42:     # ✅ Build vocabulary of Problems
  43:     def build_label_vocab(self, ann):
  44:         labels = set()
  45:
  46:         for split in ann:  # train / val / test
  47:             for sample in ann[split]:
  48:                 probs = sample.get('Problems', '')
  49:                 if probs:
  50:                     items = [p.strip() for p in probs.split(',')]
  51:                     labels.update(items)
  52:
  53:         label2idx = {l: i for i, l in enumerate(sorted(labels))}
  54:         print(f"[INFO] Total unique problem labels: {len(label2idx)}")
  55:
  56:         return label2idx
  57:
  58:     # ✅ Convert Problems → multi-hot vector
  59:     def encode_problems(self, probs):
  60:         vec = np.zeros(len(self.label2idx), dtype=np.float32)
  61:
  62:         if probs:
  63:             items = [p.strip() for p in probs.split(',')]
  64:             for item in items:
  65:                 if item in self.label2idx:
  66:                     vec[self.label2idx[item]] = 1.0
  67:
  68:         return vec
  69:
  70:
  71: # ======================================================

--- lines 27 to 72 ---
  27:
  28:         # Current split data
  29:         self.examples = self.ann[self.split]
  30:
  31:         # Tokenize reports
  32:         for i in range(len(self.examples)):
  33:             tokens = tokenizer(self.examples[i]['report'])
  34:             tokens = tokens[:self.max_seq_length]
  35:
  36:             self.examples[i]['ids'] = tokens
  37:             self.examples[i]['mask'] = [1] * len(tokens)
  38:
  39:     def __len__(self):
  40:         return len(self.examples)
  41:
  42:     # ✅ Build vocabulary of Problems
  43:     def build_label_vocab(self, ann):
  44:         labels = set()
  45:
  46:         for split in ann:  # train / val / test
  47:             for sample in ann[split]:
  48:                 probs = sample.get('Problems', '')
  49:                 if probs:
  50:                     items = [p.strip() for p in probs.split(',')]
  51:                     labels.update(items)
  52:
  53:         label2idx = {l: i for i, l in enumerate(sorted(labels))}
  54:         print(f"[INFO] Total unique problem labels: {len(label2idx)}")
  55:
  56:         return label2idx
  57:
  58:     # ✅ Convert Problems → multi-hot vector
  59:     def encode_problems(self, probs):
  60:         vec = np.zeros(len(self.label2idx), dtype=np.float32)
  61:
  62:         if probs:
  63:             items = [p.strip() for p in probs.split(',')]
  64:             for item in items:
  65:                 if item in self.label2idx:
  66:                     vec[self.label2idx[item]] = 1.0
  67:
  68:         return vec
  69:
  70:
  71: # ======================================================
  72: # IU X-RAY (2 images)

--- lines 30 to 75 ---
  30:
  31:         # Tokenize reports
  32:         for i in range(len(self.examples)):
  33:             tokens = tokenizer(self.examples[i]['report'])
  34:             tokens = tokens[:self.max_seq_length]
  35:
  36:             self.examples[i]['ids'] = tokens
  37:             self.examples[i]['mask'] = [1] * len(tokens)
  38:
  39:     def __len__(self):
  40:         return len(self.examples)
  41:
  42:     # ✅ Build vocabulary of Problems
  43:     def build_label_vocab(self, ann):
  44:         labels = set()
  45:
  46:         for split in ann:  # train / val / test
  47:             for sample in ann[split]:
  48:                 probs = sample.get('Problems', '')
  49:                 if probs:
  50:                     items = [p.strip() for p in probs.split(',')]
  51:                     labels.update(items)
  52:
  53:         label2idx = {l: i for i, l in enumerate(sorted(labels))}
  54:         print(f"[INFO] Total unique problem labels: {len(label2idx)}")
  55:
  56:         return label2idx
  57:
  58:     # ✅ Convert Problems → multi-hot vector
  59:     def encode_problems(self, probs):
  60:         vec = np.zeros(len(self.label2idx), dtype=np.float32)
  61:
  62:         if probs:
  63:             items = [p.strip() for p in probs.split(',')]
  64:             for item in items:
  65:                 if item in self.label2idx:
  66:                     vec[self.label2idx[item]] = 1.0
  67:
  68:         return vec
  69:
  70:
  71: # ======================================================
  72: # IU X-RAY (2 images)
  73: # ======================================================
  74: class IuxrayMultiImageDataset(BaseDataset):
  75:     def __getitem__(self, idx):

--- lines 66 to 111 ---
  66:                     vec[self.label2idx[item]] = 1.0
  67:
  68:         return vec
  69:
  70:
  71: # ======================================================
  72: # IU X-RAY (2 images)
  73: # ======================================================
  74: class IuxrayMultiImageDataset(BaseDataset):
  75:     def __getitem__(self, idx):
  76:         example = self.examples[idx]
  77:
  78:         image_id = example['id']
  79:         image_path = example['image_path']
  80:
  81:         # --- Load images safely ---
  82:         try:
  83:             image_1 = Image.open(os.path.join(self.image_dir, image_path[0])).convert('RGB')
  84:         except:
  85:             image_1 = Image.new('RGB', (224, 224))
  86:
  87:         if len(image_path) > 1:
  88:             try:
  89:                 image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
  90:             except:
  91:                 image_2 = image_1
  92:         else:
  93:             image_2 = image_1
  94:
  95:         # --- Apply transforms ---
  96:         if self.transform is not None:
  97:             image_1 = self.transform(image_1)

In [28]:
import sys
#sys.path.append("R2Gen")

from argparse import Namespace
from modules.tokenizers import Tokenizer
from modules.dataloaders import R2DataLoader

args = Namespace(
    image_dir="R2GenCMN/data/iu_xray/images",
    ann_path="../data/iu_xray/annotation.json",
    dataset_name="iu_xray",
    max_seq_length=60,
    threshold=3,
    num_workers=2,
    batch_size=2,
)

print("Building tokenizer...")
tokenizer = Tokenizer(args)
print("Tokenizer built.")
print("Vocab size:", len(tokenizer.token2idx))

print("\nBuilding train loader...")
train_loader = R2DataLoader(args, tokenizer, split="train", shuffle=True)

print("Fetching one batch...")
batch = next(iter(train_loader))

print("Batch loaded successfully.")
print("Batch type:", type(batch))
print("Batch length:", len(batch))

Building tokenizer...
Tokenizer built.
Vocab size: 669

Building train loader...
Fetching one batch...
Batch loaded successfully.
Batch type: <class 'tuple'>
Batch length: 4

In [29]:
for i, item in enumerate(batch):
    print(f"\nItem {i}:")
    if hasattr(item, "shape"):
        print("shape:", item.shape)
    else:
        print(type(item))
        try:
            print(item[:2])
        except:
            print(item)

Item 0:
<class 'tuple'>
('3652', '734')

Item 1:
shape: torch.Size([2, 2, 3, 224, 224])

Item 2:
shape: torch.Size([2, 8])

Item 3:
shape: torch.Size([2, 8])

In [30]:
!cat ../run_iu_xray.sh

python main.py \
  --image_dir R2GenCMN/data/iu_xray/images \
  --ann_path data/iu_xray/annotation.json \
  --dataset_name iu_xray \
  --max_seq_length 40 \
  --threshold 3 \
  --batch_size 8 \
  --epochs 5 \
  --save_dir results/iu_xray_test \
  --step_size 50 \
  --gamma 0.1 \
  --seed 9223 \
  --log_period 50 \
  --problem_dim 100 \

In [31]:
import json
import numpy as np
from pathlib import Path

ann_path = Path("../data/iu_xray/annotation.json")

with open(ann_path, "r", encoding="utf-8") as f:
    ann = json.load(f)

all_reports = []
for split in ["train", "val", "test"]:
    all_reports.extend([x["report"] for x in ann[split]])

lengths = [len(str(r).split()) for r in all_reports]

print("Num reports:", len(lengths))
print("Min:", np.min(lengths))
print("Mean:", np.mean(lengths))
print("Median:", np.median(lengths))
print("90th percentile:", np.percentile(lengths, 90))
print("95th percentile:", np.percentile(lengths, 95))
print("99th percentile:", np.percentile(lengths, 99))
print("Max:", np.max(lengths))

Num reports: 3820
Min: 1
Mean: 10.562303664921465
Median: 5.0
90th percentile: 25.0
95th percentile: 35.04999999999973
99th percentile: 56.809999999999945
Max: 130

In [32]:
from collections import Counter

img_counts = merged_df["image_filenames"].apply(len)
print(img_counts.value_counts().sort_index())

image_filenames
1     435
2    3191
3     180
4      13
5       1
Name: count, dtype: int64

In [33]:
bad_rows = merged_df[merged_df["image_filenames"].apply(len) < 2]
print("Bad rows:", len(bad_rows))
display(bad_rows[[ID_COL, TARGET_COL, "image_filenames"]].head(20))

Bad rows: 435

,uid,impression,image_filenames
43,44,No acute cardiopulmonary disease.,[44_IM-2078-1001.dcm.png]
44,45,Stable cardiomegaly without overt pulmonary ed...,[45_IM-2081-1001.dcm.png]
59,60,1. Round area of density measuring 1.9 x 1.8 c...,[60_IM-2192-1001.dcm.png]
67,68,Rib films. No fractures or dislocations. Chest...,[68_IM-2251-1001.dcm.png]
70,71,No acute cardiopulmonary disease.,[71_IM-2273-1001.dcm.png]
72,73,Improved basilar aeration. Persistent small bi...,[73_IM-2289-1001.dcm.png]
73,74,No acute pulmonary disease. Multiple thoracic ...,[74_IM-2296-2001.dcm.png]
80,81,No acute cardiopulmonary abnormality identified.,[81_IM-2343-2001.dcm.png]
87,88,1. Findings consistent with mild congestive he...,[88_IM-2394-2001.dcm.png]
90,91,Moderate sized right pneumothorax. There is mi...,[91_IM-2415-2001.dcm.png]
103,104,Minimal left basilar subsegmental atelectasis ...,[104_IM-0031-0001-0002.dcm.png]
117,119,"No acute or active cardiac, pulmonary or pleur...",[119_IM-0128-1001.dcm.png]
124,126,Vague opacity at the left lung base which appe...,[126_IM-0176-2002.dcm.png]
128,130,Clear lungs. XXXX deformities within the midth...,[130_IM-0198-2001.dcm.png]
130,132,No acute cardiopulmonary abnormality.,[132_IM-0206-1001.dcm.png]
132,134,No active disease.,[134_IM-0219-1001.dcm.png]
135,137,Some XXXX opacities left mid lung compatible w...,[137_IM-0238-2002.dcm.png]
141,144,Mild patchy bibasilar airspace disease most XX...,[144_IM-0283-1001.dcm.png]
144,147,1. No acute cardiopulmonary disease,[147_IM-0303-1001.dcm.png]
152,157,Chest. Resolving pulmonary interstitial edema ...,[157_IM-0372-1001.dcm.png]

In [34]:
from sklearn.model_selection import train_test_split
import json
from pathlib import Path
import pandas as pd

# ✅ KEEP Problems column
case_df = merged_df[[ID_COL, TARGET_COL, "image_filenames", "Problems"]].copy()

case_df = case_df.drop_duplicates(subset=[ID_COL]).reset_index(drop=True)

# keep only rows with >= 2 images
case_df = case_df[
    case_df["image_filenames"].apply(lambda x: isinstance(x, list) and len(x) >= 2)
].copy()

print("Cases with >=2 images:", len(case_df))

# keep first two images only
case_df["image_filenames"] = case_df["image_filenames"].apply(lambda x: x[:2])

# sanity check
print(case_df["image_filenames"].apply(len).value_counts())


# ================= SPLIT =================
train_df, temp_df = train_test_split(case_df, test_size=0.30, random_state=42)
val_df, test_df = train_test_split(temp_df, test_size=2/3, random_state=42)


# ================= BUILD JSON =================
def make_examples(df_split):
    examples = []
    for _, row in df_split.iterrows():

        # ✅ extract Problems safely
        problems = ""
        if "Problems" in row and not pd.isna(row["Problems"]):
            problems = str(row["Problems"]).strip()

        examples.append({
            "id": str(row[ID_COL]),
            "image_path": row["image_filenames"],
            "report": str(row[TARGET_COL]).strip(),
            "Problems": problems   # 🔥 IMPORTANT
        })

    return examples


annotation = {
    "train": make_examples(train_df),
    "val": make_examples(val_df),
    "test": make_examples(test_df),
}


# ================= SAVE =================
ann_path = Path("../data/iu_xray/annotation.json")

with open(ann_path, "w", encoding="utf-8") as f:
    json.dump(annotation, f, indent=2, ensure_ascii=False)

print("Saved:", ann_path)
print("Train:", len(annotation["train"]))
print("Val:", len(annotation["val"]))
print("Test:", len(annotation["test"]))

# 🔍 CHECK
print("Sample:", annotation["train"][0])

Cases with >=2 images: 3385
image_filenames
2    3385
Name: count, dtype: int64
Saved: ../data/iu_xray/annotation.json
Train: 2369
Val: 338
Test: 678
Sample: {'id': '499', 'image_path': ['499_IM-2116-1001.dcm.png', '499_IM-2116-2001.dcm.png'], 'report': 'No acute cardiopulmonary abnormality.', 'Problems': 'normal'}

In [35]:
import json

with open("../data/iu_xray/annotation.json", "r", encoding="utf-8") as f:
    ann = json.load(f)

for split in ["train", "val", "test"]:
    bad = [x for x in ann[split] if len(x["image_path"]) < 2]
    print(split, "bad samples:", len(bad))

train bad samples: 0
val bad samples: 0
test bad samples: 0

In [36]:
from pathlib import Path

file_path = Path("../modules/trainer.py")
text = file_path.read_text(encoding="utf-8")

text = text.replace(
    "record_table = record_table.append(self.best_record['val'], ignore_index=True)",
    "record_table = pd.concat([record_table, pd.DataFrame([self.best_record['val']])], ignore_index=True)"
)

text = text.replace(
    "record_table = record_table.append(self.best_record['test'], ignore_index=True)",
    "record_table = pd.concat([record_table, pd.DataFrame([self.best_record['test']])], ignore_index=True)"
)

file_path.write_text(text, encoding="utf-8")
print("Patched trainer.py")

Patched trainer.py

In [37]:
!grep -n "record_table = pd.concat\|append(" ../modules/trainer.py

119:        record_table = pd.concat([

In [38]:
#%cd R2Gen

!python main.py \
  --image_dir R2GenCMN/data/iu_xray/images \
  --ann_path ../data/iu_xray/annotation.json \
  --dataset_name iu_xray \
  --max_seq_length 40 \
  --threshold 3 \
  --batch_size 8 \
  --epochs 5 \
  --save_dir results/iu_xray_test \
  --step_size 50 \
  --gamma 0.1 \
  --seed 9223

/home/jupyter-st126489/.local/lib/python3.12/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/jupyter-st126489/.local/lib/python3.12/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet101_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet101_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/jupyter-st126489/NLU/Project/Progress/Ablation/R2Gen/R2Gen/main.py", line 124, in <module>
    main()
  File "/home/jupyter-st126489/NLU/Project/Progress/Ablation/R2Gen/R2Gen/main.py", line 120, in main
    trainer.train()
  File "/home/jupyter-st126489/NLU/Project/Progress/Ablation/R2Gen/R2Gen/modules/trainer.py", line 54, in train
    result = self._train_epoch(epoch)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jupyter-st126489/NLU/Project/Progress/Ablation/R2Gen/R2Gen/modules/trainer.py", line 192, in _train_epoch
    for batch_idx, (images_id, images, reports_ids, reports_masks) in enumerate(self.train_dataloader):
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jupyter-st126489/.local/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/jupyter-st126489/.local/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jupyter-st126489/.local/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/jupyter-st126489/.local/lib/python3.12/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jupyter-st126489/.local/lib/python3.12/site-packages/PIL/ImageFile.py", line 386, in load
    s = read(read_bytes)
        ^^^^^^^^^^^^^^^^
  File "/home/jupyter-st126489/.local/lib/python3.12/site-packages/PIL/PngImagePlugin.py", line 999, in load_read
    cid, pos, length = self.png.read()
                       ^^^^^^^^^^^^^^^
  File "/home/jupyter-st126489/.local/lib/python3.12/site-packages/PIL/PngImagePlugin.py", line 179, in read
    length = i32(s)
             ^^^^^^
  File "/home/jupyter-st126489/.local/lib/python3.12/site-packages/PIL/_binary.py", line 95, in i32be
    return unpack_from(">I", c, o)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack_from requires a buffer of at least 4 bytes for unpacking 4 bytes at offset 0 (actual buffer size is 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jupyter-st126489/.local/lib/python3.12/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jupyter-st126489/.local/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/jupyter-st126489/NLU/Project/Progress/Ablation/R2Gen/R2Gen/modules/datasets.py", line 33, in __getitem__
    image_2 = Image.open(os.path.join(self.image_dir, image_path[1])).convert('RGB')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jupyter-st126489/.local/lib/python3.12/site-packages/PIL/Image.py", line 967, in convert
    self.load()
  File "/home/jupyter-st126489/.local/lib/python3.12/site-packages/PIL/ImageFile.py", line 393, in load
    raise OSError(msg) from e
OSError: image file is truncated